image: golang:latest

.go-cache:
    variables:
        GOPATH: $CI_PROJECT_DIR/.go
    cache:
      paths:
        - .go/pkg/mod/



stages:          # List of stages for jobs, and their order of execution
  - lint
  - build
  - test
  # - deploy

lint:
    image: golangci/golangci-lint:latest
    stage: lint
    extends: .go-cache
    allow_failure: false
    script:
      - golangci-lint run -v



build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - make build
    - echo "Compile complete."

cross-compile:
  stage: build
  artifacts:
    name: "$CI_JOB_NAME"
    paths: 
      - bin/
    expire_in: 2 hrs

  script:
    - make compile


unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - make test



# deploy-job:      # This job runs in the deploy stage.
#   stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
#   environment: production
#   script:
#     - echo "Deploying application..."
#     - echo "Application successfully deployed."
