version: "3.7"
services:
  postgres:
    image: postgres:17
    container_name: postgres_soarca_stack
    environment:
      POSTGRES_USER: "soarca"
      POSTGRES_PASSWORD: "soarca"
      POSTGRES_DB: "soarca"
    networks:
      - db-net
    volumes:
      - postgres_data_container:/var/lib/postgresql/data

  cert-generator:
    image: alpine
    container_name: cert-generator
    volumes:
      - certs_data_containter:/certs
    environment:
      - DOMAIN=localhost
    command: >
      sh -c "
        apk add --no-cache openssl &&
        cd /certs &&
        openssl req -x509 -newkey rsa:4096 -keyout server.key -out server.crt -days 365 -nodes -subj '/CN=${DOMAIN}' &&
        chmod 644 server.key server.crt
      "

  soarca:
    build:
      dockerfile: Dockerfile
      args:
        VERSION: "${GIT_VERSION}"
    container_name: soarca_server
    volumes:
      - certs_data_containter:/app/certs
    environment:
      PORT: 8080
      ENABLE_TLS: "true"
      CERT_FILE: "/app/certs/server.crt"
      CERT_KEY_FILE: "/app/certs/server.key"
      SOARCA_ALLOWED_ORIGINS: "*"
      GIN_MODE: "release"
      DATABASE_URL: "postgres://soarca:soarca@postgres:5432/soarca?sslmode=disable"
      PLAYBOOK_API_LOG_LEVEL: trace
      HTTP_SKIP_CERT_VALIDATION: false
      AUTH_ENABLED: false #OPTIONAL for OIDC Based auth
      OIDC_PROVIDER: "https://authentikuri:9443/application/o/soarca/"
      OIDC_CLIENT_ID: "some client ID"
      OIDC_SKIP_TLS_VERIFY: false
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      - postgres
      - cert-generator

  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    command: -config.file=/etc/loki/loki-config.yaml
    volumes:
      - ./deployments/docker/soarca/observability/loki-config.yaml:/etc/loki/loki-config.yaml:ro
      - loki_data_container:/loki
    ports:
      - 127.0.0.1:3100:3100

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    command: run /etc/alloy/config.alloy
    volumes:
      - ./deployments/docker/soarca/observability/alloy-config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - loki

networks:
  db-net:

volumes:
  postgres_data_container:
  certs_data_containter:
  loki_data_container:
