// Code generated by go-swagger; DO NOT EDIT.

package contacts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// GetAPIV2ContactsReader is a Reader for the GetAPIV2Contacts structure.
type GetAPIV2ContactsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV2ContactsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV2ContactsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /api/v2/contacts] GetAPIV2Contacts", response, response.Code())
	}
}

// NewGetAPIV2ContactsOK creates a GetAPIV2ContactsOK with default headers values
func NewGetAPIV2ContactsOK() *GetAPIV2ContactsOK {
	return &GetAPIV2ContactsOK{}
}

/*
GetAPIV2ContactsOK describes a response with status code 200, with default header values.

OK
*/
type GetAPIV2ContactsOK struct {
}

// IsSuccess returns true when this get Api v2 contacts o k response has a 2xx status code
func (o *GetAPIV2ContactsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v2 contacts o k response has a 3xx status code
func (o *GetAPIV2ContactsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v2 contacts o k response has a 4xx status code
func (o *GetAPIV2ContactsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v2 contacts o k response has a 5xx status code
func (o *GetAPIV2ContactsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v2 contacts o k response a status code equal to that given
func (o *GetAPIV2ContactsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v2 contacts o k response
func (o *GetAPIV2ContactsOK) Code() int {
	return 200
}

func (o *GetAPIV2ContactsOK) Error() string {
	return fmt.Sprintf("[GET /api/v2/contacts][%d] getApiV2ContactsOK", 200)
}

func (o *GetAPIV2ContactsOK) String() string {
	return fmt.Sprintf("[GET /api/v2/contacts][%d] getApiV2ContactsOK", 200)
}

func (o *GetAPIV2ContactsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
