= Authentik OAuth Token Retrieval Client

For machine-to-machine application https://docs.goauthentik.io/docs/add-secure-apps/providers/oauth2/client_credentials[Authentik] provider m2m. In this folder we provide an example implementation. 

`BASE_URL`::
Base URL of the authentication server
* Default: `https://localhost:9443`
* Example: `https://your-auth-server.com`

`CLIENT_ID`::
OAuth client identifier
* No default value (must be provided)
* Example: `WxUcBMGZdI7c0e5oYp6mYdEd64acpXSuWKh8zBH5`

`SERVICE_ACCOUNT`::
Service account username
* No default value (must be provided)
* Example: `test2test`

`SERVICE_TOKEN`::
Service account password/token
* No default value (must be provided)
* Example: `2Dzvbs5O7wjfaUj1k1YSqctRgVA5hDtsi18xIrmKeIn1pV0rn4G5nuuFQUwH`


`SKIP_TLS_VERIFY`::
Disable TLS certificate verification
* Default: `false`

== Usage

=== Setting Environment Variables

[source,bash]
----
export BASE_URL=https://localhost:9443
export CLIENT_ID=WxUcBMGZdI7c0e5oYp6mYdEd64acpXSuWKh8zBH5
export SERVICE_ACCOUNT=test2test
export SERVICE_TOKEN=2Dzvbs5O7wjfaUj1k1YSqctRgVA5hDtsi18xIrmKeIn1pV0rn4G5nuuFQUwH
export SKIP_TLS_VERIFY=true
----

=== Running the Application

[source,bash]
----
go run main.go
----

=== Example Output

[source]
----
Access Token: <retrieved-access-token>
Token Type: Bearer
Expires In: 3600 seconds
