// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"soarca/internal/capability/caldera/api/models"
)

// NewPatchAPIV2ConfigMainParams creates a new PatchAPIV2ConfigMainParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchAPIV2ConfigMainParams() *PatchAPIV2ConfigMainParams {
	return &PatchAPIV2ConfigMainParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchAPIV2ConfigMainParamsWithTimeout creates a new PatchAPIV2ConfigMainParams object
// with the ability to set a timeout on a request.
func NewPatchAPIV2ConfigMainParamsWithTimeout(timeout time.Duration) *PatchAPIV2ConfigMainParams {
	return &PatchAPIV2ConfigMainParams{
		timeout: timeout,
	}
}

// NewPatchAPIV2ConfigMainParamsWithContext creates a new PatchAPIV2ConfigMainParams object
// with the ability to set a context for a request.
func NewPatchAPIV2ConfigMainParamsWithContext(ctx context.Context) *PatchAPIV2ConfigMainParams {
	return &PatchAPIV2ConfigMainParams{
		Context: ctx,
	}
}

// NewPatchAPIV2ConfigMainParamsWithHTTPClient creates a new PatchAPIV2ConfigMainParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchAPIV2ConfigMainParamsWithHTTPClient(client *http.Client) *PatchAPIV2ConfigMainParams {
	return &PatchAPIV2ConfigMainParams{
		HTTPClient: client,
	}
}

/*
PatchAPIV2ConfigMainParams contains all the parameters to send to the API endpoint

	for the patch API v2 config main operation.

	Typically these are written to a http.Request.
*/
type PatchAPIV2ConfigMainParams struct {

	// Body.
	Body *models.ConfigUpdate

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch API v2 config main params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchAPIV2ConfigMainParams) WithDefaults() *PatchAPIV2ConfigMainParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch API v2 config main params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchAPIV2ConfigMainParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch API v2 config main params
func (o *PatchAPIV2ConfigMainParams) WithTimeout(timeout time.Duration) *PatchAPIV2ConfigMainParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch API v2 config main params
func (o *PatchAPIV2ConfigMainParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch API v2 config main params
func (o *PatchAPIV2ConfigMainParams) WithContext(ctx context.Context) *PatchAPIV2ConfigMainParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch API v2 config main params
func (o *PatchAPIV2ConfigMainParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch API v2 config main params
func (o *PatchAPIV2ConfigMainParams) WithHTTPClient(client *http.Client) *PatchAPIV2ConfigMainParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch API v2 config main params
func (o *PatchAPIV2ConfigMainParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the patch API v2 config main params
func (o *PatchAPIV2ConfigMainParams) WithBody(body *models.ConfigUpdate) *PatchAPIV2ConfigMainParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch API v2 config main params
func (o *PatchAPIV2ConfigMainParams) SetBody(body *models.ConfigUpdate) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PatchAPIV2ConfigMainParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
