// Code generated by go-swagger; DO NOT EDIT.

package config

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"soarca/pkg/core/capability/caldera/api/models"
)

// NewPatchAPIV2ConfigAgentsParams creates a new PatchAPIV2ConfigAgentsParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchAPIV2ConfigAgentsParams() *PatchAPIV2ConfigAgentsParams {
	return &PatchAPIV2ConfigAgentsParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchAPIV2ConfigAgentsParamsWithTimeout creates a new PatchAPIV2ConfigAgentsParams object
// with the ability to set a timeout on a request.
func NewPatchAPIV2ConfigAgentsParamsWithTimeout(timeout time.Duration) *PatchAPIV2ConfigAgentsParams {
	return &PatchAPIV2ConfigAgentsParams{
		timeout: timeout,
	}
}

// NewPatchAPIV2ConfigAgentsParamsWithContext creates a new PatchAPIV2ConfigAgentsParams object
// with the ability to set a context for a request.
func NewPatchAPIV2ConfigAgentsParamsWithContext(ctx context.Context) *PatchAPIV2ConfigAgentsParams {
	return &PatchAPIV2ConfigAgentsParams{
		Context: ctx,
	}
}

// NewPatchAPIV2ConfigAgentsParamsWithHTTPClient creates a new PatchAPIV2ConfigAgentsParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchAPIV2ConfigAgentsParamsWithHTTPClient(client *http.Client) *PatchAPIV2ConfigAgentsParams {
	return &PatchAPIV2ConfigAgentsParams{
		HTTPClient: client,
	}
}

/*
PatchAPIV2ConfigAgentsParams contains all the parameters to send to the API endpoint

	for the patch API v2 config agents operation.

	Typically these are written to a http.Request.
*/
type PatchAPIV2ConfigAgentsParams struct {

	// Body.
	Body *models.AgentConfigUpdate

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch API v2 config agents params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchAPIV2ConfigAgentsParams) WithDefaults() *PatchAPIV2ConfigAgentsParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch API v2 config agents params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchAPIV2ConfigAgentsParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch API v2 config agents params
func (o *PatchAPIV2ConfigAgentsParams) WithTimeout(timeout time.Duration) *PatchAPIV2ConfigAgentsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch API v2 config agents params
func (o *PatchAPIV2ConfigAgentsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch API v2 config agents params
func (o *PatchAPIV2ConfigAgentsParams) WithContext(ctx context.Context) *PatchAPIV2ConfigAgentsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch API v2 config agents params
func (o *PatchAPIV2ConfigAgentsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch API v2 config agents params
func (o *PatchAPIV2ConfigAgentsParams) WithHTTPClient(client *http.Client) *PatchAPIV2ConfigAgentsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch API v2 config agents params
func (o *PatchAPIV2ConfigAgentsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the patch API v2 config agents params
func (o *PatchAPIV2ConfigAgentsParams) WithBody(body *models.AgentConfigUpdate) *PatchAPIV2ConfigAgentsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch API v2 config agents params
func (o *PatchAPIV2ConfigAgentsParams) SetBody(body *models.AgentConfigUpdate) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PatchAPIV2ConfigAgentsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
