// Code generated by go-swagger; DO NOT EDIT.

package agents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"soarca/pkg/core/capability/caldera/api/models"
)

// DeleteAPIV2AgentsPawReader is a Reader for the DeleteAPIV2AgentsPaw structure.
type DeleteAPIV2AgentsPawReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPIV2AgentsPawReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewDeleteAPIV2AgentsPawOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[DELETE /api/v2/agents/{paw}] DeleteAPIV2AgentsPaw", response, response.Code())
	}
}

// NewDeleteAPIV2AgentsPawOK creates a DeleteAPIV2AgentsPawOK with default headers values
func NewDeleteAPIV2AgentsPawOK() *DeleteAPIV2AgentsPawOK {
	return &DeleteAPIV2AgentsPawOK{}
}

/*
DeleteAPIV2AgentsPawOK describes a response with status code 200, with default header values.

Returns HTTP 200
*/
type DeleteAPIV2AgentsPawOK struct {
	Payload models.Agent1
}

// IsSuccess returns true when this delete Api v2 agents paw o k response has a 2xx status code
func (o *DeleteAPIV2AgentsPawOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete Api v2 agents paw o k response has a 3xx status code
func (o *DeleteAPIV2AgentsPawOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Api v2 agents paw o k response has a 4xx status code
func (o *DeleteAPIV2AgentsPawOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete Api v2 agents paw o k response has a 5xx status code
func (o *DeleteAPIV2AgentsPawOK) IsServerError() bool {
	return false
}

// IsCode returns true when this delete Api v2 agents paw o k response a status code equal to that given
func (o *DeleteAPIV2AgentsPawOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the delete Api v2 agents paw o k response
func (o *DeleteAPIV2AgentsPawOK) Code() int {
	return 200
}

func (o *DeleteAPIV2AgentsPawOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/v2/agents/{paw}][%d] deleteApiV2AgentsPawOK %s", 200, payload)
}

func (o *DeleteAPIV2AgentsPawOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[DELETE /api/v2/agents/{paw}][%d] deleteApiV2AgentsPawOK %s", 200, payload)
}

func (o *DeleteAPIV2AgentsPawOK) GetPayload() models.Agent1 {
	return o.Payload
}

func (o *DeleteAPIV2AgentsPawOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
