// Code generated by go-swagger; DO NOT EDIT.

package agents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewGetAPIV2DeployCommandsAbilityIDParams creates a new GetAPIV2DeployCommandsAbilityIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIV2DeployCommandsAbilityIDParams() *GetAPIV2DeployCommandsAbilityIDParams {
	return &GetAPIV2DeployCommandsAbilityIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV2DeployCommandsAbilityIDParamsWithTimeout creates a new GetAPIV2DeployCommandsAbilityIDParams object
// with the ability to set a timeout on a request.
func NewGetAPIV2DeployCommandsAbilityIDParamsWithTimeout(timeout time.Duration) *GetAPIV2DeployCommandsAbilityIDParams {
	return &GetAPIV2DeployCommandsAbilityIDParams{
		timeout: timeout,
	}
}

// NewGetAPIV2DeployCommandsAbilityIDParamsWithContext creates a new GetAPIV2DeployCommandsAbilityIDParams object
// with the ability to set a context for a request.
func NewGetAPIV2DeployCommandsAbilityIDParamsWithContext(ctx context.Context) *GetAPIV2DeployCommandsAbilityIDParams {
	return &GetAPIV2DeployCommandsAbilityIDParams{
		Context: ctx,
	}
}

// NewGetAPIV2DeployCommandsAbilityIDParamsWithHTTPClient creates a new GetAPIV2DeployCommandsAbilityIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIV2DeployCommandsAbilityIDParamsWithHTTPClient(client *http.Client) *GetAPIV2DeployCommandsAbilityIDParams {
	return &GetAPIV2DeployCommandsAbilityIDParams{
		HTTPClient: client,
	}
}

/*
GetAPIV2DeployCommandsAbilityIDParams contains all the parameters to send to the API endpoint

	for the get API v2 deploy commands ability ID operation.

	Typically these are written to a http.Request.
*/
type GetAPIV2DeployCommandsAbilityIDParams struct {

	/* AbilityID.

	   ID of the ability to retrieve deploy commands for
	*/
	AbilityID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API v2 deploy commands ability ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV2DeployCommandsAbilityIDParams) WithDefaults() *GetAPIV2DeployCommandsAbilityIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API v2 deploy commands ability ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV2DeployCommandsAbilityIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API v2 deploy commands ability ID params
func (o *GetAPIV2DeployCommandsAbilityIDParams) WithTimeout(timeout time.Duration) *GetAPIV2DeployCommandsAbilityIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v2 deploy commands ability ID params
func (o *GetAPIV2DeployCommandsAbilityIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v2 deploy commands ability ID params
func (o *GetAPIV2DeployCommandsAbilityIDParams) WithContext(ctx context.Context) *GetAPIV2DeployCommandsAbilityIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v2 deploy commands ability ID params
func (o *GetAPIV2DeployCommandsAbilityIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v2 deploy commands ability ID params
func (o *GetAPIV2DeployCommandsAbilityIDParams) WithHTTPClient(client *http.Client) *GetAPIV2DeployCommandsAbilityIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v2 deploy commands ability ID params
func (o *GetAPIV2DeployCommandsAbilityIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAbilityID adds the abilityID to the get API v2 deploy commands ability ID params
func (o *GetAPIV2DeployCommandsAbilityIDParams) WithAbilityID(abilityID string) *GetAPIV2DeployCommandsAbilityIDParams {
	o.SetAbilityID(abilityID)
	return o
}

// SetAbilityID adds the abilityId to the get API v2 deploy commands ability ID params
func (o *GetAPIV2DeployCommandsAbilityIDParams) SetAbilityID(abilityID string) {
	o.AbilityID = abilityID
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV2DeployCommandsAbilityIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param ability_id
	if err := r.SetPathParam("ability_id", o.AbilityID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
