// Code generated by go-swagger; DO NOT EDIT.

package agents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"soarca/pkg/core/capability/caldera/api/models"
)

// GetAPIV2AgentsReader is a Reader for the GetAPIV2Agents structure.
type GetAPIV2AgentsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV2AgentsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV2AgentsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /api/v2/agents] GetAPIV2Agents", response, response.Code())
	}
}

// NewGetAPIV2AgentsOK creates a GetAPIV2AgentsOK with default headers values
func NewGetAPIV2AgentsOK() *GetAPIV2AgentsOK {
	return &GetAPIV2AgentsOK{}
}

/*
GetAPIV2AgentsOK describes a response with status code 200, with default header values.

Returns a list of all agents.
*/
type GetAPIV2AgentsOK struct {
	Payload []*models.PartialAgent
}

// IsSuccess returns true when this get Api v2 agents o k response has a 2xx status code
func (o *GetAPIV2AgentsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v2 agents o k response has a 3xx status code
func (o *GetAPIV2AgentsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v2 agents o k response has a 4xx status code
func (o *GetAPIV2AgentsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v2 agents o k response has a 5xx status code
func (o *GetAPIV2AgentsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v2 agents o k response a status code equal to that given
func (o *GetAPIV2AgentsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v2 agents o k response
func (o *GetAPIV2AgentsOK) Code() int {
	return 200
}

func (o *GetAPIV2AgentsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/agents][%d] getApiV2AgentsOK %s", 200, payload)
}

func (o *GetAPIV2AgentsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/agents][%d] getApiV2AgentsOK %s", 200, payload)
}

func (o *GetAPIV2AgentsOK) GetPayload() []*models.PartialAgent {
	return o.Payload
}

func (o *GetAPIV2AgentsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
