// Code generated by go-swagger; DO NOT EDIT.

package agents

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"soarca/pkg/core/capability/caldera/api/models"
)

// PatchAPIV2AgentsPawReader is a Reader for the PatchAPIV2AgentsPaw structure.
type PatchAPIV2AgentsPawReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchAPIV2AgentsPawReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPatchAPIV2AgentsPawOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PATCH /api/v2/agents/{paw}] PatchAPIV2AgentsPaw", response, response.Code())
	}
}

// NewPatchAPIV2AgentsPawOK creates a PatchAPIV2AgentsPawOK with default headers values
func NewPatchAPIV2AgentsPawOK() *PatchAPIV2AgentsPawOK {
	return &PatchAPIV2AgentsPawOK{}
}

/*
PatchAPIV2AgentsPawOK describes a response with status code 200, with default header values.

Returns JSON response with updated Agent fields
*/
type PatchAPIV2AgentsPawOK struct {
	Payload *models.Agent
}

// IsSuccess returns true when this patch Api v2 agents paw o k response has a 2xx status code
func (o *PatchAPIV2AgentsPawOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this patch Api v2 agents paw o k response has a 3xx status code
func (o *PatchAPIV2AgentsPawOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch Api v2 agents paw o k response has a 4xx status code
func (o *PatchAPIV2AgentsPawOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this patch Api v2 agents paw o k response has a 5xx status code
func (o *PatchAPIV2AgentsPawOK) IsServerError() bool {
	return false
}

// IsCode returns true when this patch Api v2 agents paw o k response a status code equal to that given
func (o *PatchAPIV2AgentsPawOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the patch Api v2 agents paw o k response
func (o *PatchAPIV2AgentsPawOK) Code() int {
	return 200
}

func (o *PatchAPIV2AgentsPawOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /api/v2/agents/{paw}][%d] patchApiV2AgentsPawOK %s", 200, payload)
}

func (o *PatchAPIV2AgentsPawOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /api/v2/agents/{paw}][%d] patchApiV2AgentsPawOK %s", 200, payload)
}

func (o *PatchAPIV2AgentsPawOK) GetPayload() *models.Agent {
	return o.Payload
}

func (o *PatchAPIV2AgentsPawOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Agent)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
