// Code generated by go-swagger; DO NOT EDIT.

package schedules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteAPIV2SchedulesIDParams creates a new DeleteAPIV2SchedulesIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAPIV2SchedulesIDParams() *DeleteAPIV2SchedulesIDParams {
	return &DeleteAPIV2SchedulesIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAPIV2SchedulesIDParamsWithTimeout creates a new DeleteAPIV2SchedulesIDParams object
// with the ability to set a timeout on a request.
func NewDeleteAPIV2SchedulesIDParamsWithTimeout(timeout time.Duration) *DeleteAPIV2SchedulesIDParams {
	return &DeleteAPIV2SchedulesIDParams{
		timeout: timeout,
	}
}

// NewDeleteAPIV2SchedulesIDParamsWithContext creates a new DeleteAPIV2SchedulesIDParams object
// with the ability to set a context for a request.
func NewDeleteAPIV2SchedulesIDParamsWithContext(ctx context.Context) *DeleteAPIV2SchedulesIDParams {
	return &DeleteAPIV2SchedulesIDParams{
		Context: ctx,
	}
}

// NewDeleteAPIV2SchedulesIDParamsWithHTTPClient creates a new DeleteAPIV2SchedulesIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAPIV2SchedulesIDParamsWithHTTPClient(client *http.Client) *DeleteAPIV2SchedulesIDParams {
	return &DeleteAPIV2SchedulesIDParams{
		HTTPClient: client,
	}
}

/*
DeleteAPIV2SchedulesIDParams contains all the parameters to send to the API endpoint

	for the delete API v2 schedules ID operation.

	Typically these are written to a http.Request.
*/
type DeleteAPIV2SchedulesIDParams struct {

	/* ID.

	   UUID of the Schedule to be retrieved.
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete API v2 schedules ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIV2SchedulesIDParams) WithDefaults() *DeleteAPIV2SchedulesIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete API v2 schedules ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIV2SchedulesIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete API v2 schedules ID params
func (o *DeleteAPIV2SchedulesIDParams) WithTimeout(timeout time.Duration) *DeleteAPIV2SchedulesIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete API v2 schedules ID params
func (o *DeleteAPIV2SchedulesIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete API v2 schedules ID params
func (o *DeleteAPIV2SchedulesIDParams) WithContext(ctx context.Context) *DeleteAPIV2SchedulesIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete API v2 schedules ID params
func (o *DeleteAPIV2SchedulesIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete API v2 schedules ID params
func (o *DeleteAPIV2SchedulesIDParams) WithHTTPClient(client *http.Client) *DeleteAPIV2SchedulesIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete API v2 schedules ID params
func (o *DeleteAPIV2SchedulesIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete API v2 schedules ID params
func (o *DeleteAPIV2SchedulesIDParams) WithID(id string) *DeleteAPIV2SchedulesIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete API v2 schedules ID params
func (o *DeleteAPIV2SchedulesIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAPIV2SchedulesIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
