// Code generated by go-swagger; DO NOT EDIT.

package schedules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAPIV2SchedulesParams creates a new GetAPIV2SchedulesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIV2SchedulesParams() *GetAPIV2SchedulesParams {
	return &GetAPIV2SchedulesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV2SchedulesParamsWithTimeout creates a new GetAPIV2SchedulesParams object
// with the ability to set a timeout on a request.
func NewGetAPIV2SchedulesParamsWithTimeout(timeout time.Duration) *GetAPIV2SchedulesParams {
	return &GetAPIV2SchedulesParams{
		timeout: timeout,
	}
}

// NewGetAPIV2SchedulesParamsWithContext creates a new GetAPIV2SchedulesParams object
// with the ability to set a context for a request.
func NewGetAPIV2SchedulesParamsWithContext(ctx context.Context) *GetAPIV2SchedulesParams {
	return &GetAPIV2SchedulesParams{
		Context: ctx,
	}
}

// NewGetAPIV2SchedulesParamsWithHTTPClient creates a new GetAPIV2SchedulesParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIV2SchedulesParamsWithHTTPClient(client *http.Client) *GetAPIV2SchedulesParams {
	return &GetAPIV2SchedulesParams{
		HTTPClient: client,
	}
}

/*
GetAPIV2SchedulesParams contains all the parameters to send to the API endpoint

	for the get API v2 schedules operation.

	Typically these are written to a http.Request.
*/
type GetAPIV2SchedulesParams struct {

	// Exclude.
	Exclude []string

	// Include.
	Include []string

	// Sort.
	Sort *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API v2 schedules params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV2SchedulesParams) WithDefaults() *GetAPIV2SchedulesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API v2 schedules params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV2SchedulesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API v2 schedules params
func (o *GetAPIV2SchedulesParams) WithTimeout(timeout time.Duration) *GetAPIV2SchedulesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v2 schedules params
func (o *GetAPIV2SchedulesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v2 schedules params
func (o *GetAPIV2SchedulesParams) WithContext(ctx context.Context) *GetAPIV2SchedulesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v2 schedules params
func (o *GetAPIV2SchedulesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v2 schedules params
func (o *GetAPIV2SchedulesParams) WithHTTPClient(client *http.Client) *GetAPIV2SchedulesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v2 schedules params
func (o *GetAPIV2SchedulesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithExclude adds the exclude to the get API v2 schedules params
func (o *GetAPIV2SchedulesParams) WithExclude(exclude []string) *GetAPIV2SchedulesParams {
	o.SetExclude(exclude)
	return o
}

// SetExclude adds the exclude to the get API v2 schedules params
func (o *GetAPIV2SchedulesParams) SetExclude(exclude []string) {
	o.Exclude = exclude
}

// WithInclude adds the include to the get API v2 schedules params
func (o *GetAPIV2SchedulesParams) WithInclude(include []string) *GetAPIV2SchedulesParams {
	o.SetInclude(include)
	return o
}

// SetInclude adds the include to the get API v2 schedules params
func (o *GetAPIV2SchedulesParams) SetInclude(include []string) {
	o.Include = include
}

// WithSort adds the sort to the get API v2 schedules params
func (o *GetAPIV2SchedulesParams) WithSort(sort *string) *GetAPIV2SchedulesParams {
	o.SetSort(sort)
	return o
}

// SetSort adds the sort to the get API v2 schedules params
func (o *GetAPIV2SchedulesParams) SetSort(sort *string) {
	o.Sort = sort
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV2SchedulesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Exclude != nil {

		// binding items for exclude
		joinedExclude := o.bindParamExclude(reg)

		// query array param exclude
		if err := r.SetQueryParam("exclude", joinedExclude...); err != nil {
			return err
		}
	}

	if o.Include != nil {

		// binding items for include
		joinedInclude := o.bindParamInclude(reg)

		// query array param include
		if err := r.SetQueryParam("include", joinedInclude...); err != nil {
			return err
		}
	}

	if o.Sort != nil {

		// query param sort
		var qrSort string

		if o.Sort != nil {
			qrSort = *o.Sort
		}
		qSort := qrSort
		if qSort != "" {

			if err := r.SetQueryParam("sort", qSort); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamGetAPIV2Schedules binds the parameter exclude
func (o *GetAPIV2SchedulesParams) bindParamExclude(formats strfmt.Registry) []string {
	excludeIR := o.Exclude

	var excludeIC []string
	for _, excludeIIR := range excludeIR { // explode []string

		excludeIIV := excludeIIR // string as string
		excludeIC = append(excludeIC, excludeIIV)
	}

	// items.CollectionFormat: "multi"
	excludeIS := swag.JoinByFormat(excludeIC, "multi")

	return excludeIS
}

// bindParamGetAPIV2Schedules binds the parameter include
func (o *GetAPIV2SchedulesParams) bindParamInclude(formats strfmt.Registry) []string {
	includeIR := o.Include

	var includeIC []string
	for _, includeIIR := range includeIR { // explode []string

		includeIIV := includeIIR // string as string
		includeIC = append(includeIC, includeIIV)
	}

	// items.CollectionFormat: "multi"
	includeIS := swag.JoinByFormat(includeIC, "multi")

	return includeIS
}
