// Code generated by go-swagger; DO NOT EDIT.

package schedules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"soarca/pkg/core/capability/caldera/api/models"
)

// PatchAPIV2SchedulesIDReader is a Reader for the PatchAPIV2SchedulesID structure.
type PatchAPIV2SchedulesIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PatchAPIV2SchedulesIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPatchAPIV2SchedulesIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[PATCH /api/v2/schedules/{id}] PatchAPIV2SchedulesID", response, response.Code())
	}
}

// NewPatchAPIV2SchedulesIDOK creates a PatchAPIV2SchedulesIDOK with default headers values
func NewPatchAPIV2SchedulesIDOK() *PatchAPIV2SchedulesIDOK {
	return &PatchAPIV2SchedulesIDOK{}
}

/*
PatchAPIV2SchedulesIDOK describes a response with status code 200, with default header values.

The response is a dump of the newly updated Schedule object.
*/
type PatchAPIV2SchedulesIDOK struct {
	Payload *models.Schedule
}

// IsSuccess returns true when this patch Api v2 schedules Id o k response has a 2xx status code
func (o *PatchAPIV2SchedulesIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this patch Api v2 schedules Id o k response has a 3xx status code
func (o *PatchAPIV2SchedulesIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this patch Api v2 schedules Id o k response has a 4xx status code
func (o *PatchAPIV2SchedulesIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this patch Api v2 schedules Id o k response has a 5xx status code
func (o *PatchAPIV2SchedulesIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this patch Api v2 schedules Id o k response a status code equal to that given
func (o *PatchAPIV2SchedulesIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the patch Api v2 schedules Id o k response
func (o *PatchAPIV2SchedulesIDOK) Code() int {
	return 200
}

func (o *PatchAPIV2SchedulesIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /api/v2/schedules/{id}][%d] patchApiV2SchedulesIdOK %s", 200, payload)
}

func (o *PatchAPIV2SchedulesIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[PATCH /api/v2/schedules/{id}][%d] patchApiV2SchedulesIdOK %s", 200, payload)
}

func (o *PatchAPIV2SchedulesIDOK) GetPayload() *models.Schedule {
	return o.Payload
}

func (o *PatchAPIV2SchedulesIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Schedule)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
