// Code generated by go-swagger; DO NOT EDIT.

package schedules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"soarca/pkg/core/capability/caldera/api/models"
)

// NewPutAPIV2SchedulesIDParams creates a new PutAPIV2SchedulesIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutAPIV2SchedulesIDParams() *PutAPIV2SchedulesIDParams {
	return &PutAPIV2SchedulesIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutAPIV2SchedulesIDParamsWithTimeout creates a new PutAPIV2SchedulesIDParams object
// with the ability to set a timeout on a request.
func NewPutAPIV2SchedulesIDParamsWithTimeout(timeout time.Duration) *PutAPIV2SchedulesIDParams {
	return &PutAPIV2SchedulesIDParams{
		timeout: timeout,
	}
}

// NewPutAPIV2SchedulesIDParamsWithContext creates a new PutAPIV2SchedulesIDParams object
// with the ability to set a context for a request.
func NewPutAPIV2SchedulesIDParamsWithContext(ctx context.Context) *PutAPIV2SchedulesIDParams {
	return &PutAPIV2SchedulesIDParams{
		Context: ctx,
	}
}

// NewPutAPIV2SchedulesIDParamsWithHTTPClient creates a new PutAPIV2SchedulesIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutAPIV2SchedulesIDParamsWithHTTPClient(client *http.Client) *PutAPIV2SchedulesIDParams {
	return &PutAPIV2SchedulesIDParams{
		HTTPClient: client,
	}
}

/*
PutAPIV2SchedulesIDParams contains all the parameters to send to the API endpoint

	for the put API v2 schedules ID operation.

	Typically these are written to a http.Request.
*/
type PutAPIV2SchedulesIDParams struct {

	// Body.
	Body *models.PartialSchedule2

	/* ID.

	   UUID of the Schedule to be retrieved.
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put API v2 schedules ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIV2SchedulesIDParams) WithDefaults() *PutAPIV2SchedulesIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put API v2 schedules ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIV2SchedulesIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put API v2 schedules ID params
func (o *PutAPIV2SchedulesIDParams) WithTimeout(timeout time.Duration) *PutAPIV2SchedulesIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put API v2 schedules ID params
func (o *PutAPIV2SchedulesIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put API v2 schedules ID params
func (o *PutAPIV2SchedulesIDParams) WithContext(ctx context.Context) *PutAPIV2SchedulesIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put API v2 schedules ID params
func (o *PutAPIV2SchedulesIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put API v2 schedules ID params
func (o *PutAPIV2SchedulesIDParams) WithHTTPClient(client *http.Client) *PutAPIV2SchedulesIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put API v2 schedules ID params
func (o *PutAPIV2SchedulesIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put API v2 schedules ID params
func (o *PutAPIV2SchedulesIDParams) WithBody(body *models.PartialSchedule2) *PutAPIV2SchedulesIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put API v2 schedules ID params
func (o *PutAPIV2SchedulesIDParams) SetBody(body *models.PartialSchedule2) {
	o.Body = body
}

// WithID adds the id to the put API v2 schedules ID params
func (o *PutAPIV2SchedulesIDParams) WithID(id string) *PutAPIV2SchedulesIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put API v2 schedules ID params
func (o *PutAPIV2SchedulesIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutAPIV2SchedulesIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
