// Code generated by go-swagger; DO NOT EDIT.

package payloads

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteAPIV2PayloadsNameReader is a Reader for the DeleteAPIV2PayloadsName structure.
type DeleteAPIV2PayloadsNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteAPIV2PayloadsNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 204:
		result := NewDeleteAPIV2PayloadsNameNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 404:
		result := NewDeleteAPIV2PayloadsNameNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("[DELETE /api/v2/payloads/{name}] DeleteAPIV2PayloadsName", response, response.Code())
	}
}

// NewDeleteAPIV2PayloadsNameNoContent creates a DeleteAPIV2PayloadsNameNoContent with default headers values
func NewDeleteAPIV2PayloadsNameNoContent() *DeleteAPIV2PayloadsNameNoContent {
	return &DeleteAPIV2PayloadsNameNoContent{}
}

/*
DeleteAPIV2PayloadsNameNoContent describes a response with status code 204, with default header values.

Payload has been properly deleted.
*/
type DeleteAPIV2PayloadsNameNoContent struct {
}

// IsSuccess returns true when this delete Api v2 payloads name no content response has a 2xx status code
func (o *DeleteAPIV2PayloadsNameNoContent) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this delete Api v2 payloads name no content response has a 3xx status code
func (o *DeleteAPIV2PayloadsNameNoContent) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Api v2 payloads name no content response has a 4xx status code
func (o *DeleteAPIV2PayloadsNameNoContent) IsClientError() bool {
	return false
}

// IsServerError returns true when this delete Api v2 payloads name no content response has a 5xx status code
func (o *DeleteAPIV2PayloadsNameNoContent) IsServerError() bool {
	return false
}

// IsCode returns true when this delete Api v2 payloads name no content response a status code equal to that given
func (o *DeleteAPIV2PayloadsNameNoContent) IsCode(code int) bool {
	return code == 204
}

// Code gets the status code for the delete Api v2 payloads name no content response
func (o *DeleteAPIV2PayloadsNameNoContent) Code() int {
	return 204
}

func (o *DeleteAPIV2PayloadsNameNoContent) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/payloads/{name}][%d] deleteApiV2PayloadsNameNoContent", 204)
}

func (o *DeleteAPIV2PayloadsNameNoContent) String() string {
	return fmt.Sprintf("[DELETE /api/v2/payloads/{name}][%d] deleteApiV2PayloadsNameNoContent", 204)
}

func (o *DeleteAPIV2PayloadsNameNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteAPIV2PayloadsNameNotFound creates a DeleteAPIV2PayloadsNameNotFound with default headers values
func NewDeleteAPIV2PayloadsNameNotFound() *DeleteAPIV2PayloadsNameNotFound {
	return &DeleteAPIV2PayloadsNameNotFound{}
}

/*
DeleteAPIV2PayloadsNameNotFound describes a response with status code 404, with default header values.

Payload not found.
*/
type DeleteAPIV2PayloadsNameNotFound struct {
}

// IsSuccess returns true when this delete Api v2 payloads name not found response has a 2xx status code
func (o *DeleteAPIV2PayloadsNameNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this delete Api v2 payloads name not found response has a 3xx status code
func (o *DeleteAPIV2PayloadsNameNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this delete Api v2 payloads name not found response has a 4xx status code
func (o *DeleteAPIV2PayloadsNameNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this delete Api v2 payloads name not found response has a 5xx status code
func (o *DeleteAPIV2PayloadsNameNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this delete Api v2 payloads name not found response a status code equal to that given
func (o *DeleteAPIV2PayloadsNameNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the delete Api v2 payloads name not found response
func (o *DeleteAPIV2PayloadsNameNotFound) Code() int {
	return 404
}

func (o *DeleteAPIV2PayloadsNameNotFound) Error() string {
	return fmt.Sprintf("[DELETE /api/v2/payloads/{name}][%d] deleteApiV2PayloadsNameNotFound", 404)
}

func (o *DeleteAPIV2PayloadsNameNotFound) String() string {
	return fmt.Sprintf("[DELETE /api/v2/payloads/{name}][%d] deleteApiV2PayloadsNameNotFound", 404)
}

func (o *DeleteAPIV2PayloadsNameNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
