// Code generated by go-swagger; DO NOT EDIT.

package obfuscators

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAPIV2ObfuscatorsNameParams creates a new GetAPIV2ObfuscatorsNameParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIV2ObfuscatorsNameParams() *GetAPIV2ObfuscatorsNameParams {
	return &GetAPIV2ObfuscatorsNameParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV2ObfuscatorsNameParamsWithTimeout creates a new GetAPIV2ObfuscatorsNameParams object
// with the ability to set a timeout on a request.
func NewGetAPIV2ObfuscatorsNameParamsWithTimeout(timeout time.Duration) *GetAPIV2ObfuscatorsNameParams {
	return &GetAPIV2ObfuscatorsNameParams{
		timeout: timeout,
	}
}

// NewGetAPIV2ObfuscatorsNameParamsWithContext creates a new GetAPIV2ObfuscatorsNameParams object
// with the ability to set a context for a request.
func NewGetAPIV2ObfuscatorsNameParamsWithContext(ctx context.Context) *GetAPIV2ObfuscatorsNameParams {
	return &GetAPIV2ObfuscatorsNameParams{
		Context: ctx,
	}
}

// NewGetAPIV2ObfuscatorsNameParamsWithHTTPClient creates a new GetAPIV2ObfuscatorsNameParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIV2ObfuscatorsNameParamsWithHTTPClient(client *http.Client) *GetAPIV2ObfuscatorsNameParams {
	return &GetAPIV2ObfuscatorsNameParams{
		HTTPClient: client,
	}
}

/*
GetAPIV2ObfuscatorsNameParams contains all the parameters to send to the API endpoint

	for the get API v2 obfuscators name operation.

	Typically these are written to a http.Request.
*/
type GetAPIV2ObfuscatorsNameParams struct {

	// Exclude.
	Exclude []string

	// Include.
	Include []string

	/* Name.

	   Name of the Obfuscator
	*/
	Name string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API v2 obfuscators name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV2ObfuscatorsNameParams) WithDefaults() *GetAPIV2ObfuscatorsNameParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API v2 obfuscators name params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV2ObfuscatorsNameParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API v2 obfuscators name params
func (o *GetAPIV2ObfuscatorsNameParams) WithTimeout(timeout time.Duration) *GetAPIV2ObfuscatorsNameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v2 obfuscators name params
func (o *GetAPIV2ObfuscatorsNameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v2 obfuscators name params
func (o *GetAPIV2ObfuscatorsNameParams) WithContext(ctx context.Context) *GetAPIV2ObfuscatorsNameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v2 obfuscators name params
func (o *GetAPIV2ObfuscatorsNameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v2 obfuscators name params
func (o *GetAPIV2ObfuscatorsNameParams) WithHTTPClient(client *http.Client) *GetAPIV2ObfuscatorsNameParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v2 obfuscators name params
func (o *GetAPIV2ObfuscatorsNameParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithExclude adds the exclude to the get API v2 obfuscators name params
func (o *GetAPIV2ObfuscatorsNameParams) WithExclude(exclude []string) *GetAPIV2ObfuscatorsNameParams {
	o.SetExclude(exclude)
	return o
}

// SetExclude adds the exclude to the get API v2 obfuscators name params
func (o *GetAPIV2ObfuscatorsNameParams) SetExclude(exclude []string) {
	o.Exclude = exclude
}

// WithInclude adds the include to the get API v2 obfuscators name params
func (o *GetAPIV2ObfuscatorsNameParams) WithInclude(include []string) *GetAPIV2ObfuscatorsNameParams {
	o.SetInclude(include)
	return o
}

// SetInclude adds the include to the get API v2 obfuscators name params
func (o *GetAPIV2ObfuscatorsNameParams) SetInclude(include []string) {
	o.Include = include
}

// WithName adds the name to the get API v2 obfuscators name params
func (o *GetAPIV2ObfuscatorsNameParams) WithName(name string) *GetAPIV2ObfuscatorsNameParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the get API v2 obfuscators name params
func (o *GetAPIV2ObfuscatorsNameParams) SetName(name string) {
	o.Name = name
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV2ObfuscatorsNameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Exclude != nil {

		// binding items for exclude
		joinedExclude := o.bindParamExclude(reg)

		// query array param exclude
		if err := r.SetQueryParam("exclude", joinedExclude...); err != nil {
			return err
		}
	}

	if o.Include != nil {

		// binding items for include
		joinedInclude := o.bindParamInclude(reg)

		// query array param include
		if err := r.SetQueryParam("include", joinedInclude...); err != nil {
			return err
		}
	}

	// path param name
	if err := r.SetPathParam("name", o.Name); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamGetAPIV2ObfuscatorsName binds the parameter exclude
func (o *GetAPIV2ObfuscatorsNameParams) bindParamExclude(formats strfmt.Registry) []string {
	excludeIR := o.Exclude

	var excludeIC []string
	for _, excludeIIR := range excludeIR { // explode []string

		excludeIIV := excludeIIR // string as string
		excludeIC = append(excludeIC, excludeIIV)
	}

	// items.CollectionFormat: "multi"
	excludeIS := swag.JoinByFormat(excludeIC, "multi")

	return excludeIS
}

// bindParamGetAPIV2ObfuscatorsName binds the parameter include
func (o *GetAPIV2ObfuscatorsNameParams) bindParamInclude(formats strfmt.Registry) []string {
	includeIR := o.Include

	var includeIC []string
	for _, includeIIR := range includeIR { // explode []string

		includeIIV := includeIIR // string as string
		includeIC = append(includeIC, includeIIV)
	}

	// items.CollectionFormat: "multi"
	includeIS := swag.JoinByFormat(includeIC, "multi")

	return includeIS
}
