// Code generated by go-swagger; DO NOT EDIT.

package obfuscators

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"soarca/internal/capability/caldera/api/models"
)

// HeadAPIV2ObfuscatorsNameReader is a Reader for the HeadAPIV2ObfuscatorsName structure.
type HeadAPIV2ObfuscatorsNameReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *HeadAPIV2ObfuscatorsNameReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewHeadAPIV2ObfuscatorsNameOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[HEAD /api/v2/obfuscators/{name}] HeadAPIV2ObfuscatorsName", response, response.Code())
	}
}

// NewHeadAPIV2ObfuscatorsNameOK creates a HeadAPIV2ObfuscatorsNameOK with default headers values
func NewHeadAPIV2ObfuscatorsNameOK() *HeadAPIV2ObfuscatorsNameOK {
	return &HeadAPIV2ObfuscatorsNameOK{}
}

/*
HeadAPIV2ObfuscatorsNameOK describes a response with status code 200, with default header values.

Returns the specified obfuscator in ObfuscatorSchema format.
*/
type HeadAPIV2ObfuscatorsNameOK struct {
	Payload *models.PartialObfuscator
}

// IsSuccess returns true when this head Api v2 obfuscators name o k response has a 2xx status code
func (o *HeadAPIV2ObfuscatorsNameOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this head Api v2 obfuscators name o k response has a 3xx status code
func (o *HeadAPIV2ObfuscatorsNameOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this head Api v2 obfuscators name o k response has a 4xx status code
func (o *HeadAPIV2ObfuscatorsNameOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this head Api v2 obfuscators name o k response has a 5xx status code
func (o *HeadAPIV2ObfuscatorsNameOK) IsServerError() bool {
	return false
}

// IsCode returns true when this head Api v2 obfuscators name o k response a status code equal to that given
func (o *HeadAPIV2ObfuscatorsNameOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the head Api v2 obfuscators name o k response
func (o *HeadAPIV2ObfuscatorsNameOK) Code() int {
	return 200
}

func (o *HeadAPIV2ObfuscatorsNameOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[HEAD /api/v2/obfuscators/{name}][%d] headApiV2ObfuscatorsNameOK %s", 200, payload)
}

func (o *HeadAPIV2ObfuscatorsNameOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[HEAD /api/v2/obfuscators/{name}][%d] headApiV2ObfuscatorsNameOK %s", 200, payload)
}

func (o *HeadAPIV2ObfuscatorsNameOK) GetPayload() *models.PartialObfuscator {
	return o.Payload
}

func (o *HeadAPIV2ObfuscatorsNameOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PartialObfuscator)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
