// Code generated by go-swagger; DO NOT EDIT.

package obfuscators

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"soarca/internal/capability/caldera/api/models"
)

// HeadAPIV2ObfuscatorsReader is a Reader for the HeadAPIV2Obfuscators structure.
type HeadAPIV2ObfuscatorsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *HeadAPIV2ObfuscatorsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewHeadAPIV2ObfuscatorsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[HEAD /api/v2/obfuscators] HeadAPIV2Obfuscators", response, response.Code())
	}
}

// NewHeadAPIV2ObfuscatorsOK creates a HeadAPIV2ObfuscatorsOK with default headers values
func NewHeadAPIV2ObfuscatorsOK() *HeadAPIV2ObfuscatorsOK {
	return &HeadAPIV2ObfuscatorsOK{}
}

/*
HeadAPIV2ObfuscatorsOK describes a response with status code 200, with default header values.

Returns a list of all obfuscators in ObfuscatorSchema format.
*/
type HeadAPIV2ObfuscatorsOK struct {
	Payload []*models.PartialObfuscator
}

// IsSuccess returns true when this head Api v2 obfuscators o k response has a 2xx status code
func (o *HeadAPIV2ObfuscatorsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this head Api v2 obfuscators o k response has a 3xx status code
func (o *HeadAPIV2ObfuscatorsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this head Api v2 obfuscators o k response has a 4xx status code
func (o *HeadAPIV2ObfuscatorsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this head Api v2 obfuscators o k response has a 5xx status code
func (o *HeadAPIV2ObfuscatorsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this head Api v2 obfuscators o k response a status code equal to that given
func (o *HeadAPIV2ObfuscatorsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the head Api v2 obfuscators o k response
func (o *HeadAPIV2ObfuscatorsOK) Code() int {
	return 200
}

func (o *HeadAPIV2ObfuscatorsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[HEAD /api/v2/obfuscators][%d] headApiV2ObfuscatorsOK %s", 200, payload)
}

func (o *HeadAPIV2ObfuscatorsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[HEAD /api/v2/obfuscators][%d] headApiV2ObfuscatorsOK %s", 200, payload)
}

func (o *HeadAPIV2ObfuscatorsOK) GetPayload() []*models.PartialObfuscator {
	return o.Payload
}

func (o *HeadAPIV2ObfuscatorsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
