= SOARCA controller

The SOARCA controller will control the incoming calls and the execution of steps. 

[plantuml, target=soar-ca-controller-components]
....
@startuml

interface IWorkflow{
    void Get()
    void Get(PlaybookId id)
    void Add(Playbook workflow)
    void Update(Playbook workflow)
    void Remove(Playbook workflow)
}

interface ICoa{
    void GetAll()
    void Get(CoaId id)
    void Add(Playbook coa)
    void Update(Playbook coa)
    void Remove(Playbook coa)
    
}

interface IStatus{

}

interface ITrigger{
    void LoadAndStartPlaybook(PlaybookId id)
}

Interface IPlaybookDatabase

Interface IDatabase
Interface IQueue
Interface IDecomposer
Interface IExecuter

class Controller
class Decomposer
class PlaybookDatabase
class File
class Mongo
class Queue
Class Executer


IWorkflow <|.. Controller
ICoa <|.. Controller
ITrigger <|.. Controller
IStatus <|.. Controller
IQueue <|.. Queue
IExecuter <|.. Executer
Controller -> IPlaybookDatabase
IPlaybookDatabase <|.. PlaybookDatabase
IDatabase <-up- PlaybookDatabase
IDatabase <|.. File
IDatabase <|.. Mongo
IDecomposer <- Controller
IDecomposer <|.. Decomposer
IExecuter -> Decomposer
IQueue -> Executer
@enduml
....
