= SOARCA Executer design

The document contains the design considerations of the executer of SOARCA

== Components

The executer consists of 3 components. 

. The playbook decomposer (parser)
. The command executor
. The command queue


[plantuml, target=soar-ca-executer-components]
....
@startuml

package "Controller" {
component Decomposer as parser
component "Queue MQTT" as queue
}
package "Executor" {
component Executor2 as exe2
component Executor1 as exe1
}
parser -- queue
queue -- Executor
@enduml
....



== Executor interface

[plantuml, target=soar-ca-executer-interface]
....
@startuml

interface IExecutor {
}

struct State{
    stopped
    running
    paused
}


struct Step {
    type
    name
    description
    external_reference
    delay
    timeout
    step_variable
    owner
    on_completion
    on_succes
    on_failure
    step_extensions
}


interface IModule {
    void Execute(command, variable, module)
    void RegisterOnCompletionHandler(OnCompletion)
}


class Executor {
    void SetState(State)
}

class Module
protocol ProtoBuffer

IExecutor <|.. Executor
Executor -> IModule
IModule <|.. Module
Module - ProtoBuffer


@enduml
....


https://github.com/phf/go-queue

== Protocol

=== Sending a step

Variables can be input and output the CACAO spec should declare the following fields for variables:
direction : input|output


And every step that will output any variables should declare a list of output variables:
output: var_1

[plantuml, target=soar-ca-executer-step-message]
....
@startjson
{
        "execute-id" : "uuid",
        "output-variables" : ["some-var", "another-var"],
        "step": {
            "step_uuid": "step--a76dbc32-b739-427b-ae13-4ec703d5797e",
            "type": "action",
            "name": "IMC assets by CVE",
            "description": "Check the IMC for affected assets by CVE",
            "on_completion": "step--9fcc5c3b-0b70-4d73-b922-cf5491dcd1a4",
            "commands": [
                {
                    "type": "http-api",
                    "command": "GET http://__imc_address__/by/__cve__"
                }
            ]
        }
}
@endjson
....

=== Result

[plantuml, target=soar-ca-executer-result-message]
....
@startjson
{
       
        "execute-id" : "uuid",
        "executer-module-id" : "<your module id>",
        "status" : "ok|error|failed",
        "completion-time" : "2023-05-26T15:56:00.123456Z",
        "results" : [{ 
            "return-variable" : "<$$some-var$$>",
            "result-typ" : "bool|int|ip-address|uri|MACADDRESS|domain-name|custom",
            "result" : "<your result here>"
        },
        { 
            "return-variable" : "another-var",
            "result-typ" : "bool|int|ip-address|uri|mac-address|domain-name|custom",
            "result" : "<your result here>"
        }
        ]
}
@endjson
....

==== Default schemas

. bool
. int
. ip-address
. uri
. mac-address
. domain-name


==== Example schema


== Sequences 

