// Code generated by go-swagger; DO NOT EDIT.

package plugins

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"soarca/pkg/core/capability/caldera/api/models"
)

// HeadAPIV2PluginsReader is a Reader for the HeadAPIV2Plugins structure.
type HeadAPIV2PluginsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *HeadAPIV2PluginsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewHeadAPIV2PluginsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[HEAD /api/v2/plugins] HeadAPIV2Plugins", response, response.Code())
	}
}

// NewHeadAPIV2PluginsOK creates a HeadAPIV2PluginsOK with default headers values
func NewHeadAPIV2PluginsOK() *HeadAPIV2PluginsOK {
	return &HeadAPIV2PluginsOK{}
}

/*
HeadAPIV2PluginsOK describes a response with status code 200, with default header values.

Returns a list in `PluginSchema` format of all available plugins in the system.
*/
type HeadAPIV2PluginsOK struct {
	Payload []*models.PartialPlugin
}

// IsSuccess returns true when this head Api v2 plugins o k response has a 2xx status code
func (o *HeadAPIV2PluginsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this head Api v2 plugins o k response has a 3xx status code
func (o *HeadAPIV2PluginsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this head Api v2 plugins o k response has a 4xx status code
func (o *HeadAPIV2PluginsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this head Api v2 plugins o k response has a 5xx status code
func (o *HeadAPIV2PluginsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this head Api v2 plugins o k response a status code equal to that given
func (o *HeadAPIV2PluginsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the head Api v2 plugins o k response
func (o *HeadAPIV2PluginsOK) Code() int {
	return 200
}

func (o *HeadAPIV2PluginsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[HEAD /api/v2/plugins][%d] headApiV2PluginsOK %s", 200, payload)
}

func (o *HeadAPIV2PluginsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[HEAD /api/v2/plugins][%d] headApiV2PluginsOK %s", 200, payload)
}

func (o *HeadAPIV2PluginsOK) GetPayload() []*models.PartialPlugin {
	return o.Payload
}

func (o *HeadAPIV2PluginsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
