// Code generated by go-swagger; DO NOT EDIT.

package abilities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"soarca/internal/capability/caldera/api/models"
)

// GetAPIV2AbilitiesAbilityIDReader is a Reader for the GetAPIV2AbilitiesAbilityID structure.
type GetAPIV2AbilitiesAbilityIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV2AbilitiesAbilityIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV2AbilitiesAbilityIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /api/v2/abilities/{ability_id}] GetAPIV2AbilitiesAbilityID", response, response.Code())
	}
}

// NewGetAPIV2AbilitiesAbilityIDOK creates a GetAPIV2AbilitiesAbilityIDOK with default headers values
func NewGetAPIV2AbilitiesAbilityIDOK() *GetAPIV2AbilitiesAbilityIDOK {
	return &GetAPIV2AbilitiesAbilityIDOK{}
}

/*
GetAPIV2AbilitiesAbilityIDOK describes a response with status code 200, with default header values.

JSON dictionary representation of the existing Ability.
*/
type GetAPIV2AbilitiesAbilityIDOK struct {
	Payload *models.PartialAbility
}

// IsSuccess returns true when this get Api v2 abilities ability Id o k response has a 2xx status code
func (o *GetAPIV2AbilitiesAbilityIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v2 abilities ability Id o k response has a 3xx status code
func (o *GetAPIV2AbilitiesAbilityIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v2 abilities ability Id o k response has a 4xx status code
func (o *GetAPIV2AbilitiesAbilityIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v2 abilities ability Id o k response has a 5xx status code
func (o *GetAPIV2AbilitiesAbilityIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v2 abilities ability Id o k response a status code equal to that given
func (o *GetAPIV2AbilitiesAbilityIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v2 abilities ability Id o k response
func (o *GetAPIV2AbilitiesAbilityIDOK) Code() int {
	return 200
}

func (o *GetAPIV2AbilitiesAbilityIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/abilities/{ability_id}][%d] getApiV2AbilitiesAbilityIdOK %s", 200, payload)
}

func (o *GetAPIV2AbilitiesAbilityIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/abilities/{ability_id}][%d] getApiV2AbilitiesAbilityIdOK %s", 200, payload)
}

func (o *GetAPIV2AbilitiesAbilityIDOK) GetPayload() *models.PartialAbility {
	return o.Payload
}

func (o *GetAPIV2AbilitiesAbilityIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PartialAbility)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
