// Code generated by go-swagger; DO NOT EDIT.

package abilities

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"soarca/pkg/core/capability/caldera/api/models"
)

// NewPostAPIV2AbilitiesParams creates a new PostAPIV2AbilitiesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPostAPIV2AbilitiesParams() *PostAPIV2AbilitiesParams {
	return &PostAPIV2AbilitiesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPostAPIV2AbilitiesParamsWithTimeout creates a new PostAPIV2AbilitiesParams object
// with the ability to set a timeout on a request.
func NewPostAPIV2AbilitiesParamsWithTimeout(timeout time.Duration) *PostAPIV2AbilitiesParams {
	return &PostAPIV2AbilitiesParams{
		timeout: timeout,
	}
}

// NewPostAPIV2AbilitiesParamsWithContext creates a new PostAPIV2AbilitiesParams object
// with the ability to set a context for a request.
func NewPostAPIV2AbilitiesParamsWithContext(ctx context.Context) *PostAPIV2AbilitiesParams {
	return &PostAPIV2AbilitiesParams{
		Context: ctx,
	}
}

// NewPostAPIV2AbilitiesParamsWithHTTPClient creates a new PostAPIV2AbilitiesParams object
// with the ability to set a custom HTTPClient for a request.
func NewPostAPIV2AbilitiesParamsWithHTTPClient(client *http.Client) *PostAPIV2AbilitiesParams {
	return &PostAPIV2AbilitiesParams{
		HTTPClient: client,
	}
}

/*
PostAPIV2AbilitiesParams contains all the parameters to send to the API endpoint

	for the post API v2 abilities operation.

	Typically these are written to a http.Request.
*/
type PostAPIV2AbilitiesParams struct {

	// Body.
	Body *models.Ability

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the post API v2 abilities params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV2AbilitiesParams) WithDefaults() *PostAPIV2AbilitiesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the post API v2 abilities params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PostAPIV2AbilitiesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the post API v2 abilities params
func (o *PostAPIV2AbilitiesParams) WithTimeout(timeout time.Duration) *PostAPIV2AbilitiesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post API v2 abilities params
func (o *PostAPIV2AbilitiesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post API v2 abilities params
func (o *PostAPIV2AbilitiesParams) WithContext(ctx context.Context) *PostAPIV2AbilitiesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post API v2 abilities params
func (o *PostAPIV2AbilitiesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the post API v2 abilities params
func (o *PostAPIV2AbilitiesParams) WithHTTPClient(client *http.Client) *PostAPIV2AbilitiesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the post API v2 abilities params
func (o *PostAPIV2AbilitiesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the post API v2 abilities params
func (o *PostAPIV2AbilitiesParams) WithBody(body *models.Ability) *PostAPIV2AbilitiesParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post API v2 abilities params
func (o *PostAPIV2AbilitiesParams) SetBody(body *models.Ability) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostAPIV2AbilitiesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
