// Code generated by go-swagger; DO NOT EDIT.

package planners

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewHeadAPIV2PlannersPlannerIDParams creates a new HeadAPIV2PlannersPlannerIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewHeadAPIV2PlannersPlannerIDParams() *HeadAPIV2PlannersPlannerIDParams {
	return &HeadAPIV2PlannersPlannerIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewHeadAPIV2PlannersPlannerIDParamsWithTimeout creates a new HeadAPIV2PlannersPlannerIDParams object
// with the ability to set a timeout on a request.
func NewHeadAPIV2PlannersPlannerIDParamsWithTimeout(timeout time.Duration) *HeadAPIV2PlannersPlannerIDParams {
	return &HeadAPIV2PlannersPlannerIDParams{
		timeout: timeout,
	}
}

// NewHeadAPIV2PlannersPlannerIDParamsWithContext creates a new HeadAPIV2PlannersPlannerIDParams object
// with the ability to set a context for a request.
func NewHeadAPIV2PlannersPlannerIDParamsWithContext(ctx context.Context) *HeadAPIV2PlannersPlannerIDParams {
	return &HeadAPIV2PlannersPlannerIDParams{
		Context: ctx,
	}
}

// NewHeadAPIV2PlannersPlannerIDParamsWithHTTPClient creates a new HeadAPIV2PlannersPlannerIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewHeadAPIV2PlannersPlannerIDParamsWithHTTPClient(client *http.Client) *HeadAPIV2PlannersPlannerIDParams {
	return &HeadAPIV2PlannersPlannerIDParams{
		HTTPClient: client,
	}
}

/*
HeadAPIV2PlannersPlannerIDParams contains all the parameters to send to the API endpoint

	for the head API v2 planners planner ID operation.

	Typically these are written to a http.Request.
*/
type HeadAPIV2PlannersPlannerIDParams struct {

	// Exclude.
	Exclude []string

	// Include.
	Include []string

	/* PlannerID.

	   UUID of the Planner object to be retrieved.
	*/
	PlannerID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the head API v2 planners planner ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HeadAPIV2PlannersPlannerIDParams) WithDefaults() *HeadAPIV2PlannersPlannerIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the head API v2 planners planner ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HeadAPIV2PlannersPlannerIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the head API v2 planners planner ID params
func (o *HeadAPIV2PlannersPlannerIDParams) WithTimeout(timeout time.Duration) *HeadAPIV2PlannersPlannerIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the head API v2 planners planner ID params
func (o *HeadAPIV2PlannersPlannerIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the head API v2 planners planner ID params
func (o *HeadAPIV2PlannersPlannerIDParams) WithContext(ctx context.Context) *HeadAPIV2PlannersPlannerIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the head API v2 planners planner ID params
func (o *HeadAPIV2PlannersPlannerIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the head API v2 planners planner ID params
func (o *HeadAPIV2PlannersPlannerIDParams) WithHTTPClient(client *http.Client) *HeadAPIV2PlannersPlannerIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the head API v2 planners planner ID params
func (o *HeadAPIV2PlannersPlannerIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithExclude adds the exclude to the head API v2 planners planner ID params
func (o *HeadAPIV2PlannersPlannerIDParams) WithExclude(exclude []string) *HeadAPIV2PlannersPlannerIDParams {
	o.SetExclude(exclude)
	return o
}

// SetExclude adds the exclude to the head API v2 planners planner ID params
func (o *HeadAPIV2PlannersPlannerIDParams) SetExclude(exclude []string) {
	o.Exclude = exclude
}

// WithInclude adds the include to the head API v2 planners planner ID params
func (o *HeadAPIV2PlannersPlannerIDParams) WithInclude(include []string) *HeadAPIV2PlannersPlannerIDParams {
	o.SetInclude(include)
	return o
}

// SetInclude adds the include to the head API v2 planners planner ID params
func (o *HeadAPIV2PlannersPlannerIDParams) SetInclude(include []string) {
	o.Include = include
}

// WithPlannerID adds the plannerID to the head API v2 planners planner ID params
func (o *HeadAPIV2PlannersPlannerIDParams) WithPlannerID(plannerID string) *HeadAPIV2PlannersPlannerIDParams {
	o.SetPlannerID(plannerID)
	return o
}

// SetPlannerID adds the plannerId to the head API v2 planners planner ID params
func (o *HeadAPIV2PlannersPlannerIDParams) SetPlannerID(plannerID string) {
	o.PlannerID = plannerID
}

// WriteToRequest writes these params to a swagger request
func (o *HeadAPIV2PlannersPlannerIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Exclude != nil {

		// binding items for exclude
		joinedExclude := o.bindParamExclude(reg)

		// query array param exclude
		if err := r.SetQueryParam("exclude", joinedExclude...); err != nil {
			return err
		}
	}

	if o.Include != nil {

		// binding items for include
		joinedInclude := o.bindParamInclude(reg)

		// query array param include
		if err := r.SetQueryParam("include", joinedInclude...); err != nil {
			return err
		}
	}

	// path param planner_id
	if err := r.SetPathParam("planner_id", o.PlannerID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamHeadAPIV2PlannersPlannerID binds the parameter exclude
func (o *HeadAPIV2PlannersPlannerIDParams) bindParamExclude(formats strfmt.Registry) []string {
	excludeIR := o.Exclude

	var excludeIC []string
	for _, excludeIIR := range excludeIR { // explode []string

		excludeIIV := excludeIIR // string as string
		excludeIC = append(excludeIC, excludeIIV)
	}

	// items.CollectionFormat: "multi"
	excludeIS := swag.JoinByFormat(excludeIC, "multi")

	return excludeIS
}

// bindParamHeadAPIV2PlannersPlannerID binds the parameter include
func (o *HeadAPIV2PlannersPlannerIDParams) bindParamInclude(formats strfmt.Registry) []string {
	includeIR := o.Include

	var includeIC []string
	for _, includeIIR := range includeIR { // explode []string

		includeIIV := includeIIR // string as string
		includeIC = append(includeIC, includeIIV)
	}

	// items.CollectionFormat: "multi"
	includeIS := swag.JoinByFormat(includeIC, "multi")

	return includeIS
}
