// Code generated by go-swagger; DO NOT EDIT.

package planners

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"soarca/internal/capability/caldera/api/models"
)

// HeadAPIV2PlannersReader is a Reader for the HeadAPIV2Planners structure.
type HeadAPIV2PlannersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *HeadAPIV2PlannersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewHeadAPIV2PlannersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[HEAD /api/v2/planners] HeadAPIV2Planners", response, response.Code())
	}
}

// NewHeadAPIV2PlannersOK creates a HeadAPIV2PlannersOK with default headers values
func NewHeadAPIV2PlannersOK() *HeadAPIV2PlannersOK {
	return &HeadAPIV2PlannersOK{}
}

/*
HeadAPIV2PlannersOK describes a response with status code 200, with default header values.

Returns a list of matching planners in `PlannerSchema` format.
*/
type HeadAPIV2PlannersOK struct {
	Payload []*models.PartialPlanner
}

// IsSuccess returns true when this head Api v2 planners o k response has a 2xx status code
func (o *HeadAPIV2PlannersOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this head Api v2 planners o k response has a 3xx status code
func (o *HeadAPIV2PlannersOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this head Api v2 planners o k response has a 4xx status code
func (o *HeadAPIV2PlannersOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this head Api v2 planners o k response has a 5xx status code
func (o *HeadAPIV2PlannersOK) IsServerError() bool {
	return false
}

// IsCode returns true when this head Api v2 planners o k response a status code equal to that given
func (o *HeadAPIV2PlannersOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the head Api v2 planners o k response
func (o *HeadAPIV2PlannersOK) Code() int {
	return 200
}

func (o *HeadAPIV2PlannersOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[HEAD /api/v2/planners][%d] headApiV2PlannersOK %s", 200, payload)
}

func (o *HeadAPIV2PlannersOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[HEAD /api/v2/planners][%d] headApiV2PlannersOK %s", 200, payload)
}

func (o *HeadAPIV2PlannersOK) GetPayload() []*models.PartialPlanner {
	return o.Payload
}

func (o *HeadAPIV2PlannersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
