// Code generated by go-swagger; DO NOT EDIT.

package operationsops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewGetAPIV2OperationsIDPotentialLinksPawParams creates a new GetAPIV2OperationsIDPotentialLinksPawParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewGetAPIV2OperationsIDPotentialLinksPawParams() *GetAPIV2OperationsIDPotentialLinksPawParams {
	return &GetAPIV2OperationsIDPotentialLinksPawParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewGetAPIV2OperationsIDPotentialLinksPawParamsWithTimeout creates a new GetAPIV2OperationsIDPotentialLinksPawParams object
// with the ability to set a timeout on a request.
func NewGetAPIV2OperationsIDPotentialLinksPawParamsWithTimeout(timeout time.Duration) *GetAPIV2OperationsIDPotentialLinksPawParams {
	return &GetAPIV2OperationsIDPotentialLinksPawParams{
		timeout: timeout,
	}
}

// NewGetAPIV2OperationsIDPotentialLinksPawParamsWithContext creates a new GetAPIV2OperationsIDPotentialLinksPawParams object
// with the ability to set a context for a request.
func NewGetAPIV2OperationsIDPotentialLinksPawParamsWithContext(ctx context.Context) *GetAPIV2OperationsIDPotentialLinksPawParams {
	return &GetAPIV2OperationsIDPotentialLinksPawParams{
		Context: ctx,
	}
}

// NewGetAPIV2OperationsIDPotentialLinksPawParamsWithHTTPClient creates a new GetAPIV2OperationsIDPotentialLinksPawParams object
// with the ability to set a custom HTTPClient for a request.
func NewGetAPIV2OperationsIDPotentialLinksPawParamsWithHTTPClient(client *http.Client) *GetAPIV2OperationsIDPotentialLinksPawParams {
	return &GetAPIV2OperationsIDPotentialLinksPawParams{
		HTTPClient: client,
	}
}

/*
GetAPIV2OperationsIDPotentialLinksPawParams contains all the parameters to send to the API endpoint

	for the get API v2 operations ID potential links paw operation.

	Typically these are written to a http.Request.
*/
type GetAPIV2OperationsIDPotentialLinksPawParams struct {

	// Exclude.
	Exclude []string

	/* ID.

	   String UUID of the Operation containing desired links.
	*/
	ID string

	// Include.
	Include []string

	/* Paw.

	   Agent paw for the specified operation.
	*/
	Paw string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the get API v2 operations ID potential links paw params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV2OperationsIDPotentialLinksPawParams) WithDefaults() *GetAPIV2OperationsIDPotentialLinksPawParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the get API v2 operations ID potential links paw params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *GetAPIV2OperationsIDPotentialLinksPawParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the get API v2 operations ID potential links paw params
func (o *GetAPIV2OperationsIDPotentialLinksPawParams) WithTimeout(timeout time.Duration) *GetAPIV2OperationsIDPotentialLinksPawParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get API v2 operations ID potential links paw params
func (o *GetAPIV2OperationsIDPotentialLinksPawParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get API v2 operations ID potential links paw params
func (o *GetAPIV2OperationsIDPotentialLinksPawParams) WithContext(ctx context.Context) *GetAPIV2OperationsIDPotentialLinksPawParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get API v2 operations ID potential links paw params
func (o *GetAPIV2OperationsIDPotentialLinksPawParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get API v2 operations ID potential links paw params
func (o *GetAPIV2OperationsIDPotentialLinksPawParams) WithHTTPClient(client *http.Client) *GetAPIV2OperationsIDPotentialLinksPawParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get API v2 operations ID potential links paw params
func (o *GetAPIV2OperationsIDPotentialLinksPawParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithExclude adds the exclude to the get API v2 operations ID potential links paw params
func (o *GetAPIV2OperationsIDPotentialLinksPawParams) WithExclude(exclude []string) *GetAPIV2OperationsIDPotentialLinksPawParams {
	o.SetExclude(exclude)
	return o
}

// SetExclude adds the exclude to the get API v2 operations ID potential links paw params
func (o *GetAPIV2OperationsIDPotentialLinksPawParams) SetExclude(exclude []string) {
	o.Exclude = exclude
}

// WithID adds the id to the get API v2 operations ID potential links paw params
func (o *GetAPIV2OperationsIDPotentialLinksPawParams) WithID(id string) *GetAPIV2OperationsIDPotentialLinksPawParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the get API v2 operations ID potential links paw params
func (o *GetAPIV2OperationsIDPotentialLinksPawParams) SetID(id string) {
	o.ID = id
}

// WithInclude adds the include to the get API v2 operations ID potential links paw params
func (o *GetAPIV2OperationsIDPotentialLinksPawParams) WithInclude(include []string) *GetAPIV2OperationsIDPotentialLinksPawParams {
	o.SetInclude(include)
	return o
}

// SetInclude adds the include to the get API v2 operations ID potential links paw params
func (o *GetAPIV2OperationsIDPotentialLinksPawParams) SetInclude(include []string) {
	o.Include = include
}

// WithPaw adds the paw to the get API v2 operations ID potential links paw params
func (o *GetAPIV2OperationsIDPotentialLinksPawParams) WithPaw(paw string) *GetAPIV2OperationsIDPotentialLinksPawParams {
	o.SetPaw(paw)
	return o
}

// SetPaw adds the paw to the get API v2 operations ID potential links paw params
func (o *GetAPIV2OperationsIDPotentialLinksPawParams) SetPaw(paw string) {
	o.Paw = paw
}

// WriteToRequest writes these params to a swagger request
func (o *GetAPIV2OperationsIDPotentialLinksPawParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Exclude != nil {

		// binding items for exclude
		joinedExclude := o.bindParamExclude(reg)

		// query array param exclude
		if err := r.SetQueryParam("exclude", joinedExclude...); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.Include != nil {

		// binding items for include
		joinedInclude := o.bindParamInclude(reg)

		// query array param include
		if err := r.SetQueryParam("include", joinedInclude...); err != nil {
			return err
		}
	}

	// path param paw
	if err := r.SetPathParam("paw", o.Paw); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamGetAPIV2OperationsIDPotentialLinksPaw binds the parameter exclude
func (o *GetAPIV2OperationsIDPotentialLinksPawParams) bindParamExclude(formats strfmt.Registry) []string {
	excludeIR := o.Exclude

	var excludeIC []string
	for _, excludeIIR := range excludeIR { // explode []string

		excludeIIV := excludeIIR // string as string
		excludeIC = append(excludeIC, excludeIIV)
	}

	// items.CollectionFormat: "multi"
	excludeIS := swag.JoinByFormat(excludeIC, "multi")

	return excludeIS
}

// bindParamGetAPIV2OperationsIDPotentialLinksPaw binds the parameter include
func (o *GetAPIV2OperationsIDPotentialLinksPawParams) bindParamInclude(formats strfmt.Registry) []string {
	includeIR := o.Include

	var includeIC []string
	for _, includeIIR := range includeIR { // explode []string

		includeIIV := includeIIR // string as string
		includeIC = append(includeIC, includeIIV)
	}

	// items.CollectionFormat: "multi"
	includeIS := swag.JoinByFormat(includeIC, "multi")

	return includeIS
}
