// Code generated by go-swagger; DO NOT EDIT.

package operationsops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewHeadAPIV2OperationsIDLinksLinkIDParams creates a new HeadAPIV2OperationsIDLinksLinkIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewHeadAPIV2OperationsIDLinksLinkIDParams() *HeadAPIV2OperationsIDLinksLinkIDParams {
	return &HeadAPIV2OperationsIDLinksLinkIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewHeadAPIV2OperationsIDLinksLinkIDParamsWithTimeout creates a new HeadAPIV2OperationsIDLinksLinkIDParams object
// with the ability to set a timeout on a request.
func NewHeadAPIV2OperationsIDLinksLinkIDParamsWithTimeout(timeout time.Duration) *HeadAPIV2OperationsIDLinksLinkIDParams {
	return &HeadAPIV2OperationsIDLinksLinkIDParams{
		timeout: timeout,
	}
}

// NewHeadAPIV2OperationsIDLinksLinkIDParamsWithContext creates a new HeadAPIV2OperationsIDLinksLinkIDParams object
// with the ability to set a context for a request.
func NewHeadAPIV2OperationsIDLinksLinkIDParamsWithContext(ctx context.Context) *HeadAPIV2OperationsIDLinksLinkIDParams {
	return &HeadAPIV2OperationsIDLinksLinkIDParams{
		Context: ctx,
	}
}

// NewHeadAPIV2OperationsIDLinksLinkIDParamsWithHTTPClient creates a new HeadAPIV2OperationsIDLinksLinkIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewHeadAPIV2OperationsIDLinksLinkIDParamsWithHTTPClient(client *http.Client) *HeadAPIV2OperationsIDLinksLinkIDParams {
	return &HeadAPIV2OperationsIDLinksLinkIDParams{
		HTTPClient: client,
	}
}

/*
HeadAPIV2OperationsIDLinksLinkIDParams contains all the parameters to send to the API endpoint

	for the head API v2 operations ID links link ID operation.

	Typically these are written to a http.Request.
*/
type HeadAPIV2OperationsIDLinksLinkIDParams struct {

	// Exclude.
	Exclude []string

	/* ID.

	   String UUID of the Operation containing desired link.
	*/
	ID string

	// Include.
	Include []string

	/* LinkID.

	   String UUID of the Link with the above operation.
	*/
	LinkID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the head API v2 operations ID links link ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HeadAPIV2OperationsIDLinksLinkIDParams) WithDefaults() *HeadAPIV2OperationsIDLinksLinkIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the head API v2 operations ID links link ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HeadAPIV2OperationsIDLinksLinkIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the head API v2 operations ID links link ID params
func (o *HeadAPIV2OperationsIDLinksLinkIDParams) WithTimeout(timeout time.Duration) *HeadAPIV2OperationsIDLinksLinkIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the head API v2 operations ID links link ID params
func (o *HeadAPIV2OperationsIDLinksLinkIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the head API v2 operations ID links link ID params
func (o *HeadAPIV2OperationsIDLinksLinkIDParams) WithContext(ctx context.Context) *HeadAPIV2OperationsIDLinksLinkIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the head API v2 operations ID links link ID params
func (o *HeadAPIV2OperationsIDLinksLinkIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the head API v2 operations ID links link ID params
func (o *HeadAPIV2OperationsIDLinksLinkIDParams) WithHTTPClient(client *http.Client) *HeadAPIV2OperationsIDLinksLinkIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the head API v2 operations ID links link ID params
func (o *HeadAPIV2OperationsIDLinksLinkIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithExclude adds the exclude to the head API v2 operations ID links link ID params
func (o *HeadAPIV2OperationsIDLinksLinkIDParams) WithExclude(exclude []string) *HeadAPIV2OperationsIDLinksLinkIDParams {
	o.SetExclude(exclude)
	return o
}

// SetExclude adds the exclude to the head API v2 operations ID links link ID params
func (o *HeadAPIV2OperationsIDLinksLinkIDParams) SetExclude(exclude []string) {
	o.Exclude = exclude
}

// WithID adds the id to the head API v2 operations ID links link ID params
func (o *HeadAPIV2OperationsIDLinksLinkIDParams) WithID(id string) *HeadAPIV2OperationsIDLinksLinkIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the head API v2 operations ID links link ID params
func (o *HeadAPIV2OperationsIDLinksLinkIDParams) SetID(id string) {
	o.ID = id
}

// WithInclude adds the include to the head API v2 operations ID links link ID params
func (o *HeadAPIV2OperationsIDLinksLinkIDParams) WithInclude(include []string) *HeadAPIV2OperationsIDLinksLinkIDParams {
	o.SetInclude(include)
	return o
}

// SetInclude adds the include to the head API v2 operations ID links link ID params
func (o *HeadAPIV2OperationsIDLinksLinkIDParams) SetInclude(include []string) {
	o.Include = include
}

// WithLinkID adds the linkID to the head API v2 operations ID links link ID params
func (o *HeadAPIV2OperationsIDLinksLinkIDParams) WithLinkID(linkID string) *HeadAPIV2OperationsIDLinksLinkIDParams {
	o.SetLinkID(linkID)
	return o
}

// SetLinkID adds the linkId to the head API v2 operations ID links link ID params
func (o *HeadAPIV2OperationsIDLinksLinkIDParams) SetLinkID(linkID string) {
	o.LinkID = linkID
}

// WriteToRequest writes these params to a swagger request
func (o *HeadAPIV2OperationsIDLinksLinkIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Exclude != nil {

		// binding items for exclude
		joinedExclude := o.bindParamExclude(reg)

		// query array param exclude
		if err := r.SetQueryParam("exclude", joinedExclude...); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.Include != nil {

		// binding items for include
		joinedInclude := o.bindParamInclude(reg)

		// query array param include
		if err := r.SetQueryParam("include", joinedInclude...); err != nil {
			return err
		}
	}

	// path param link_id
	if err := r.SetPathParam("link_id", o.LinkID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamHeadAPIV2OperationsIDLinksLinkID binds the parameter exclude
func (o *HeadAPIV2OperationsIDLinksLinkIDParams) bindParamExclude(formats strfmt.Registry) []string {
	excludeIR := o.Exclude

	var excludeIC []string
	for _, excludeIIR := range excludeIR { // explode []string

		excludeIIV := excludeIIR // string as string
		excludeIC = append(excludeIC, excludeIIV)
	}

	// items.CollectionFormat: "multi"
	excludeIS := swag.JoinByFormat(excludeIC, "multi")

	return excludeIS
}

// bindParamHeadAPIV2OperationsIDLinksLinkID binds the parameter include
func (o *HeadAPIV2OperationsIDLinksLinkIDParams) bindParamInclude(formats strfmt.Registry) []string {
	includeIR := o.Include

	var includeIC []string
	for _, includeIIR := range includeIR { // explode []string

		includeIIV := includeIIR // string as string
		includeIC = append(includeIC, includeIIV)
	}

	// items.CollectionFormat: "multi"
	includeIS := swag.JoinByFormat(includeIC, "multi")

	return includeIS
}
