// Code generated by go-swagger; DO NOT EDIT.

package operationsops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"soarca/internal/capability/caldera/api/models"
)

// HeadAPIV2OperationsIDReader is a Reader for the HeadAPIV2OperationsID structure.
type HeadAPIV2OperationsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *HeadAPIV2OperationsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewHeadAPIV2OperationsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[HEAD /api/v2/operations/{id}] HeadAPIV2OperationsID", response, response.Code())
	}
}

// NewHeadAPIV2OperationsIDOK creates a HeadAPIV2OperationsIDOK with default headers values
func NewHeadAPIV2OperationsIDOK() *HeadAPIV2OperationsIDOK {
	return &HeadAPIV2OperationsIDOK{}
}

/*
HeadAPIV2OperationsIDOK describes a response with status code 200, with default header values.

The response is the operation with the specified id, if any.
*/
type HeadAPIV2OperationsIDOK struct {
	Payload *models.PartialOperation
}

// IsSuccess returns true when this head Api v2 operations Id o k response has a 2xx status code
func (o *HeadAPIV2OperationsIDOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this head Api v2 operations Id o k response has a 3xx status code
func (o *HeadAPIV2OperationsIDOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this head Api v2 operations Id o k response has a 4xx status code
func (o *HeadAPIV2OperationsIDOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this head Api v2 operations Id o k response has a 5xx status code
func (o *HeadAPIV2OperationsIDOK) IsServerError() bool {
	return false
}

// IsCode returns true when this head Api v2 operations Id o k response a status code equal to that given
func (o *HeadAPIV2OperationsIDOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the head Api v2 operations Id o k response
func (o *HeadAPIV2OperationsIDOK) Code() int {
	return 200
}

func (o *HeadAPIV2OperationsIDOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[HEAD /api/v2/operations/{id}][%d] headApiV2OperationsIdOK %s", 200, payload)
}

func (o *HeadAPIV2OperationsIDOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[HEAD /api/v2/operations/{id}][%d] headApiV2OperationsIdOK %s", 200, payload)
}

func (o *HeadAPIV2OperationsIDOK) GetPayload() *models.PartialOperation {
	return o.Payload
}

func (o *HeadAPIV2OperationsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PartialOperation)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
