// Code generated by go-swagger; DO NOT EDIT.

package operationsops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"soarca/pkg/core/capability/caldera/api/models"
)

// NewPatchAPIV2OperationsIDLinksLinkIDParams creates a new PatchAPIV2OperationsIDLinksLinkIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchAPIV2OperationsIDLinksLinkIDParams() *PatchAPIV2OperationsIDLinksLinkIDParams {
	return &PatchAPIV2OperationsIDLinksLinkIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchAPIV2OperationsIDLinksLinkIDParamsWithTimeout creates a new PatchAPIV2OperationsIDLinksLinkIDParams object
// with the ability to set a timeout on a request.
func NewPatchAPIV2OperationsIDLinksLinkIDParamsWithTimeout(timeout time.Duration) *PatchAPIV2OperationsIDLinksLinkIDParams {
	return &PatchAPIV2OperationsIDLinksLinkIDParams{
		timeout: timeout,
	}
}

// NewPatchAPIV2OperationsIDLinksLinkIDParamsWithContext creates a new PatchAPIV2OperationsIDLinksLinkIDParams object
// with the ability to set a context for a request.
func NewPatchAPIV2OperationsIDLinksLinkIDParamsWithContext(ctx context.Context) *PatchAPIV2OperationsIDLinksLinkIDParams {
	return &PatchAPIV2OperationsIDLinksLinkIDParams{
		Context: ctx,
	}
}

// NewPatchAPIV2OperationsIDLinksLinkIDParamsWithHTTPClient creates a new PatchAPIV2OperationsIDLinksLinkIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchAPIV2OperationsIDLinksLinkIDParamsWithHTTPClient(client *http.Client) *PatchAPIV2OperationsIDLinksLinkIDParams {
	return &PatchAPIV2OperationsIDLinksLinkIDParams{
		HTTPClient: client,
	}
}

/*
PatchAPIV2OperationsIDLinksLinkIDParams contains all the parameters to send to the API endpoint

	for the patch API v2 operations ID links link ID operation.

	Typically these are written to a http.Request.
*/
type PatchAPIV2OperationsIDLinksLinkIDParams struct {

	// Body.
	Body *models.PartialLink1

	/* ID.

	   String UUID of the Operation containing desired link.
	*/
	ID string

	/* LinkID.

	   String UUID of the Link with the above operation.
	*/
	LinkID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch API v2 operations ID links link ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchAPIV2OperationsIDLinksLinkIDParams) WithDefaults() *PatchAPIV2OperationsIDLinksLinkIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch API v2 operations ID links link ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchAPIV2OperationsIDLinksLinkIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch API v2 operations ID links link ID params
func (o *PatchAPIV2OperationsIDLinksLinkIDParams) WithTimeout(timeout time.Duration) *PatchAPIV2OperationsIDLinksLinkIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch API v2 operations ID links link ID params
func (o *PatchAPIV2OperationsIDLinksLinkIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch API v2 operations ID links link ID params
func (o *PatchAPIV2OperationsIDLinksLinkIDParams) WithContext(ctx context.Context) *PatchAPIV2OperationsIDLinksLinkIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch API v2 operations ID links link ID params
func (o *PatchAPIV2OperationsIDLinksLinkIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch API v2 operations ID links link ID params
func (o *PatchAPIV2OperationsIDLinksLinkIDParams) WithHTTPClient(client *http.Client) *PatchAPIV2OperationsIDLinksLinkIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch API v2 operations ID links link ID params
func (o *PatchAPIV2OperationsIDLinksLinkIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the patch API v2 operations ID links link ID params
func (o *PatchAPIV2OperationsIDLinksLinkIDParams) WithBody(body *models.PartialLink1) *PatchAPIV2OperationsIDLinksLinkIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch API v2 operations ID links link ID params
func (o *PatchAPIV2OperationsIDLinksLinkIDParams) SetBody(body *models.PartialLink1) {
	o.Body = body
}

// WithID adds the id to the patch API v2 operations ID links link ID params
func (o *PatchAPIV2OperationsIDLinksLinkIDParams) WithID(id string) *PatchAPIV2OperationsIDLinksLinkIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the patch API v2 operations ID links link ID params
func (o *PatchAPIV2OperationsIDLinksLinkIDParams) SetID(id string) {
	o.ID = id
}

// WithLinkID adds the linkID to the patch API v2 operations ID links link ID params
func (o *PatchAPIV2OperationsIDLinksLinkIDParams) WithLinkID(linkID string) *PatchAPIV2OperationsIDLinksLinkIDParams {
	o.SetLinkID(linkID)
	return o
}

// SetLinkID adds the linkId to the patch API v2 operations ID links link ID params
func (o *PatchAPIV2OperationsIDLinksLinkIDParams) SetLinkID(linkID string) {
	o.LinkID = linkID
}

// WriteToRequest writes these params to a swagger request
func (o *PatchAPIV2OperationsIDLinksLinkIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	// path param link_id
	if err := r.SetPathParam("link_id", o.LinkID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
