// Code generated by go-swagger; DO NOT EDIT.

package operationsops

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"soarca/internal/capability/caldera/api/models"
)

// PostAPIV2OperationsIDEventLogsReader is a Reader for the PostAPIV2OperationsIDEventLogs structure.
type PostAPIV2OperationsIDEventLogsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV2OperationsIDEventLogsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIV2OperationsIDEventLogsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /api/v2/operations/{id}/event-logs] PostAPIV2OperationsIDEventLogs", response, response.Code())
	}
}

// NewPostAPIV2OperationsIDEventLogsOK creates a PostAPIV2OperationsIDEventLogsOK with default headers values
func NewPostAPIV2OperationsIDEventLogsOK() *PostAPIV2OperationsIDEventLogsOK {
	return &PostAPIV2OperationsIDEventLogsOK{}
}

/*
PostAPIV2OperationsIDEventLogsOK describes a response with status code 200, with default header values.

PostAPIV2OperationsIDEventLogsOK post Api v2 operations Id event logs o k
*/
type PostAPIV2OperationsIDEventLogsOK struct {
	Payload *models.OperationOutputRequest
}

// IsSuccess returns true when this post Api v2 operations Id event logs o k response has a 2xx status code
func (o *PostAPIV2OperationsIDEventLogsOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api v2 operations Id event logs o k response has a 3xx status code
func (o *PostAPIV2OperationsIDEventLogsOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v2 operations Id event logs o k response has a 4xx status code
func (o *PostAPIV2OperationsIDEventLogsOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v2 operations Id event logs o k response has a 5xx status code
func (o *PostAPIV2OperationsIDEventLogsOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v2 operations Id event logs o k response a status code equal to that given
func (o *PostAPIV2OperationsIDEventLogsOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post Api v2 operations Id event logs o k response
func (o *PostAPIV2OperationsIDEventLogsOK) Code() int {
	return 200
}

func (o *PostAPIV2OperationsIDEventLogsOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v2/operations/{id}/event-logs][%d] postApiV2OperationsIdEventLogsOK %s", 200, payload)
}

func (o *PostAPIV2OperationsIDEventLogsOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v2/operations/{id}/event-logs][%d] postApiV2OperationsIdEventLogsOK %s", 200, payload)
}

func (o *PostAPIV2OperationsIDEventLogsOK) GetPayload() *models.OperationOutputRequest {
	return o.Payload
}

func (o *PostAPIV2OperationsIDEventLogsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OperationOutputRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
