services:
  mongodb_container:
    image: docker.io/mongo:latest
    container_name: mongo_soarca_stack
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "rootpassword"
    networks:
      - db-net
    volumes:
      - type: volume
        source: mongodb_data_container
        target: /data/db

  caldera:
    image: soarca-caldera
    build: https://github.com/mitre/caldera.git
    networks:
      - caldera-net
    ports:
      - "8888:8888"
      - "8443:8443"
      - "7010:7010"
      - "7011:7011/udp"
      - "7012:7012"
      - "8853:8853"
      - "8022:8022"
      - "2222:2222"
    profiles:
      - caldera

  mosquitto:
    image: docker.io/eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - type: volume
        source: mosquitto_config
        target: /mosquitto/config
      - type: volume
        source: mosquitto_data
        target: /mosquitto/data
      - type: volume
        source: mosquitto_log
        target: /mosquitto/log
    networks:
      - mqtt-net
    ports:
      - target: 1883
        published: 1883
        protocol: tcp
        mode: host
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host

  soarca:
    image: docker.io/cossas/soarca:latest
    container_name: soarca_server
    environment:
      PORT: 8080
      SOARCA_ALLOWED_ORIGINS: "*"
      GIN_MODE: "release"
      MONGODB_URI: "mongodb://mongodb_container:27017"
      DATABASE_NAME: "soarca"
      DB_USERNAME: "root"
      DB_PASSWORD: "rootpassword"
      PLAYBOOK_API_LOG_LEVEL: trace
      DATABASE: "true"
      LOG_GLOBAL_LEVEL: "info"
      LOG_MODE: "production"
      LOG_FILE_PATH: ""
      LOG_FORMAT: "json"
      ENABLE_FINS: true
      MQTT_BROKER: "mosquitto"
      MQTT_PORT: 1883
      HTTP_SKIP_CERT_VALIDATION: false
      # Integrations:
      # The Hive
      THEHIVE_ACTIVATE: false
      THEHIVE_API_TOKEN: your_token
      THEHIVE_API_BASE_URL: http://localhost:9000/api/v1/
      CALDERA_HOST: "caldera"
      CALDERA_PORT: "8888"
      CALDERA_API: "ADMIN123"
    networks:
      - db-net
      - mqtt-net
      - caldera-net
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      - mongodb_container
      - mosquitto

networks:
  db-net:
  mqtt-net:
  caldera-net:

volumes:
  mongodb_data_container:
  mosquitto_config:
    driver: local # Define the driver and options under the volume name
    driver_opts:
      type: none
      device: ./config
      o: bind
  mosquitto_data:
  mosquitto_log:
