// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Adjustment adjustment
//
// swagger:model Adjustment
type Adjustment struct {

	// ability id
	AbilityID string `json:"ability_id,omitempty"`

	// offset
	Offset int64 `json:"offset,omitempty"`

	// trait
	Trait string `json:"trait,omitempty"`

	// value
	Value string `json:"value,omitempty"`
}

// Validate validates this adjustment
func (m *Adjustment) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this adjustment based on context it is used
func (m *Adjustment) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Adjustment) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Adjustment) UnmarshalBinary(b []byte) error {
	var res Adjustment
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
