// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ConfigUpdate config update
//
// swagger:model ConfigUpdate
type ConfigUpdate struct {

	// prop
	// Required: true
	Prop *string `json:"prop"`

	// value
	// Required: true
	Value *string `json:"value"`
}

// Validate validates this config update
func (m *ConfigUpdate) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateProp(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ConfigUpdate) validateProp(formats strfmt.Registry) error {

	if err := validate.Required("prop", "body", m.Prop); err != nil {
		return err
	}

	return nil
}

func (m *ConfigUpdate) validateValue(formats strfmt.Registry) error {

	if err := validate.Required("value", "body", m.Value); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this config update based on context it is used
func (m *ConfigUpdate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ConfigUpdate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ConfigUpdate) UnmarshalBinary(b []byte) error {
	var res ConfigUpdate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
