// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Objective objective
//
// swagger:model Objective
type Objective struct {

	// description
	Description string `json:"description,omitempty"`

	// goals
	Goals []*Goal `json:"goals"`

	// id
	ID string `json:"id,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// percentage
	// Read Only: true
	Percentage float64 `json:"percentage,omitempty"`
}

// Validate validates this objective
func (m *Objective) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateGoals(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Objective) validateGoals(formats strfmt.Registry) error {
	if swag.IsZero(m.Goals) { // not required
		return nil
	}

	for i := 0; i < len(m.Goals); i++ {
		if swag.IsZero(m.Goals[i]) { // not required
			continue
		}

		if m.Goals[i] != nil {
			if err := m.Goals[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("goals" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("goals" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this objective based on the context it is used
func (m *Objective) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateGoals(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePercentage(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Objective) contextValidateGoals(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Goals); i++ {

		if m.Goals[i] != nil {

			if swag.IsZero(m.Goals[i]) { // not required
				return nil
			}

			if err := m.Goals[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("goals" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("goals" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *Objective) contextValidatePercentage(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "percentage", "body", float64(m.Percentage)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *Objective) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Objective) UnmarshalBinary(b []byte) error {
	var res Objective
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
