// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// PartialRelationshipUpdate partial relationship update
//
// swagger:model Partial-RelationshipUpdate
type PartialRelationshipUpdate struct {

	// criteria
	Criteria *PartialRelationship `json:"criteria,omitempty"`

	// updates
	Updates *PartialRelationship `json:"updates,omitempty"`
}

// Validate validates this partial relationship update
func (m *PartialRelationshipUpdate) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCriteria(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUpdates(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PartialRelationshipUpdate) validateCriteria(formats strfmt.Registry) error {
	if swag.IsZero(m.Criteria) { // not required
		return nil
	}

	if m.Criteria != nil {
		if err := m.Criteria.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("criteria")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("criteria")
			}
			return err
		}
	}

	return nil
}

func (m *PartialRelationshipUpdate) validateUpdates(formats strfmt.Registry) error {
	if swag.IsZero(m.Updates) { // not required
		return nil
	}

	if m.Updates != nil {
		if err := m.Updates.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("updates")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("updates")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this partial relationship update based on the context it is used
func (m *PartialRelationshipUpdate) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCriteria(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateUpdates(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PartialRelationshipUpdate) contextValidateCriteria(ctx context.Context, formats strfmt.Registry) error {

	if m.Criteria != nil {

		if swag.IsZero(m.Criteria) { // not required
			return nil
		}

		if err := m.Criteria.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("criteria")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("criteria")
			}
			return err
		}
	}

	return nil
}

func (m *PartialRelationshipUpdate) contextValidateUpdates(ctx context.Context, formats strfmt.Registry) error {

	if m.Updates != nil {

		if swag.IsZero(m.Updates) { // not required
			return nil
		}

		if err := m.Updates.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("updates")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("updates")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PartialRelationshipUpdate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PartialRelationshipUpdate) UnmarshalBinary(b []byte) error {
	var res PartialRelationshipUpdate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
