// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PartialOperationSchemaAlt partial operation schema alt
//
// swagger:model Partial-OperationSchemaAlt
type PartialOperationSchemaAlt struct {

	// adversary
	Adversary *Adversary `json:"adversary,omitempty"`

	// agents
	Agents map[string]Agent `json:"agents,omitempty"`

	// auto close
	AutoClose bool `json:"auto_close,omitempty"`

	// autonomous
	Autonomous int64 `json:"autonomous,omitempty"`

	// chain
	// Read Only: true
	Chain interface{} `json:"chain,omitempty"`

	// group
	Group string `json:"group,omitempty"`

	// host group
	// Read Only: true
	HostGroup []*Agent `json:"host_group"`

	// hosts
	Hosts map[string]Host `json:"hosts,omitempty"`

	// id
	ID string `json:"id,omitempty"`

	// jitter
	Jitter string `json:"jitter,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// obfuscator
	Obfuscator string `json:"obfuscator,omitempty"`

	// objective
	Objective *Objective `json:"objective,omitempty"`

	// planner
	Planner *Planner `json:"planner,omitempty"`

	// source
	Source *Source `json:"source,omitempty"`

	// start
	// Read Only: true
	Start string `json:"start,omitempty"`

	// state
	State string `json:"state,omitempty"`

	// use learning parsers
	UseLearningParsers bool `json:"use_learning_parsers,omitempty"`

	// visibility
	Visibility int64 `json:"visibility,omitempty"`
}

// Validate validates this partial operation schema alt
func (m *PartialOperationSchemaAlt) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAdversary(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateAgents(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateHostGroup(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateHosts(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateObjective(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validatePlanner(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSource(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PartialOperationSchemaAlt) validateAdversary(formats strfmt.Registry) error {
	if swag.IsZero(m.Adversary) { // not required
		return nil
	}

	if m.Adversary != nil {
		if err := m.Adversary.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("adversary")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("adversary")
			}
			return err
		}
	}

	return nil
}

func (m *PartialOperationSchemaAlt) validateAgents(formats strfmt.Registry) error {
	if swag.IsZero(m.Agents) { // not required
		return nil
	}

	for k := range m.Agents {

		if err := validate.Required("agents"+"."+k, "body", m.Agents[k]); err != nil {
			return err
		}
		if val, ok := m.Agents[k]; ok {
			if err := val.Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("agents" + "." + k)
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("agents" + "." + k)
				}
				return err
			}
		}

	}

	return nil
}

func (m *PartialOperationSchemaAlt) validateHostGroup(formats strfmt.Registry) error {
	if swag.IsZero(m.HostGroup) { // not required
		return nil
	}

	for i := 0; i < len(m.HostGroup); i++ {
		if swag.IsZero(m.HostGroup[i]) { // not required
			continue
		}

		if m.HostGroup[i] != nil {
			if err := m.HostGroup[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("host_group" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("host_group" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *PartialOperationSchemaAlt) validateHosts(formats strfmt.Registry) error {
	if swag.IsZero(m.Hosts) { // not required
		return nil
	}

	for k := range m.Hosts {

		if err := validate.Required("hosts"+"."+k, "body", m.Hosts[k]); err != nil {
			return err
		}
		if val, ok := m.Hosts[k]; ok {
			if err := val.Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("hosts" + "." + k)
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("hosts" + "." + k)
				}
				return err
			}
		}

	}

	return nil
}

func (m *PartialOperationSchemaAlt) validateObjective(formats strfmt.Registry) error {
	if swag.IsZero(m.Objective) { // not required
		return nil
	}

	if m.Objective != nil {
		if err := m.Objective.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("objective")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("objective")
			}
			return err
		}
	}

	return nil
}

func (m *PartialOperationSchemaAlt) validatePlanner(formats strfmt.Registry) error {
	if swag.IsZero(m.Planner) { // not required
		return nil
	}

	if m.Planner != nil {
		if err := m.Planner.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("planner")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("planner")
			}
			return err
		}
	}

	return nil
}

func (m *PartialOperationSchemaAlt) validateSource(formats strfmt.Registry) error {
	if swag.IsZero(m.Source) { // not required
		return nil
	}

	if m.Source != nil {
		if err := m.Source.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("source")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("source")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this partial operation schema alt based on the context it is used
func (m *PartialOperationSchemaAlt) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAdversary(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateAgents(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateHostGroup(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateHosts(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateObjective(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidatePlanner(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSource(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateStart(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PartialOperationSchemaAlt) contextValidateAdversary(ctx context.Context, formats strfmt.Registry) error {

	if m.Adversary != nil {

		if swag.IsZero(m.Adversary) { // not required
			return nil
		}

		if err := m.Adversary.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("adversary")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("adversary")
			}
			return err
		}
	}

	return nil
}

func (m *PartialOperationSchemaAlt) contextValidateAgents(ctx context.Context, formats strfmt.Registry) error {

	for k := range m.Agents {

		if val, ok := m.Agents[k]; ok {
			if err := val.ContextValidate(ctx, formats); err != nil {
				return err
			}
		}

	}

	return nil
}

func (m *PartialOperationSchemaAlt) contextValidateHostGroup(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "host_group", "body", []*Agent(m.HostGroup)); err != nil {
		return err
	}

	for i := 0; i < len(m.HostGroup); i++ {

		if m.HostGroup[i] != nil {

			if swag.IsZero(m.HostGroup[i]) { // not required
				return nil
			}

			if err := m.HostGroup[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("host_group" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("host_group" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *PartialOperationSchemaAlt) contextValidateHosts(ctx context.Context, formats strfmt.Registry) error {

	for k := range m.Hosts {

		if val, ok := m.Hosts[k]; ok {
			if err := val.ContextValidate(ctx, formats); err != nil {
				return err
			}
		}

	}

	return nil
}

func (m *PartialOperationSchemaAlt) contextValidateObjective(ctx context.Context, formats strfmt.Registry) error {

	if m.Objective != nil {

		if swag.IsZero(m.Objective) { // not required
			return nil
		}

		if err := m.Objective.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("objective")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("objective")
			}
			return err
		}
	}

	return nil
}

func (m *PartialOperationSchemaAlt) contextValidatePlanner(ctx context.Context, formats strfmt.Registry) error {

	if m.Planner != nil {

		if swag.IsZero(m.Planner) { // not required
			return nil
		}

		if err := m.Planner.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("planner")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("planner")
			}
			return err
		}
	}

	return nil
}

func (m *PartialOperationSchemaAlt) contextValidateSource(ctx context.Context, formats strfmt.Registry) error {

	if m.Source != nil {

		if swag.IsZero(m.Source) { // not required
			return nil
		}

		if err := m.Source.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("source")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("source")
			}
			return err
		}
	}

	return nil
}

func (m *PartialOperationSchemaAlt) contextValidateStart(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "start", "body", string(m.Start)); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PartialOperationSchemaAlt) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PartialOperationSchemaAlt) UnmarshalBinary(b []byte) error {
	var res PartialOperationSchemaAlt
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
