// Code generated by go-swagger; DO NOT EDIT.

package objectives

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewHeadAPIV2ObjectivesIDParams creates a new HeadAPIV2ObjectivesIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewHeadAPIV2ObjectivesIDParams() *HeadAPIV2ObjectivesIDParams {
	return &HeadAPIV2ObjectivesIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewHeadAPIV2ObjectivesIDParamsWithTimeout creates a new HeadAPIV2ObjectivesIDParams object
// with the ability to set a timeout on a request.
func NewHeadAPIV2ObjectivesIDParamsWithTimeout(timeout time.Duration) *HeadAPIV2ObjectivesIDParams {
	return &HeadAPIV2ObjectivesIDParams{
		timeout: timeout,
	}
}

// NewHeadAPIV2ObjectivesIDParamsWithContext creates a new HeadAPIV2ObjectivesIDParams object
// with the ability to set a context for a request.
func NewHeadAPIV2ObjectivesIDParamsWithContext(ctx context.Context) *HeadAPIV2ObjectivesIDParams {
	return &HeadAPIV2ObjectivesIDParams{
		Context: ctx,
	}
}

// NewHeadAPIV2ObjectivesIDParamsWithHTTPClient creates a new HeadAPIV2ObjectivesIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewHeadAPIV2ObjectivesIDParamsWithHTTPClient(client *http.Client) *HeadAPIV2ObjectivesIDParams {
	return &HeadAPIV2ObjectivesIDParams{
		HTTPClient: client,
	}
}

/*
HeadAPIV2ObjectivesIDParams contains all the parameters to send to the API endpoint

	for the head API v2 objectives ID operation.

	Typically these are written to a http.Request.
*/
type HeadAPIV2ObjectivesIDParams struct {

	// Exclude.
	Exclude []string

	/* ID.

	   UUID of the objective to be retrieved
	*/
	ID string

	// Include.
	Include []string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the head API v2 objectives ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HeadAPIV2ObjectivesIDParams) WithDefaults() *HeadAPIV2ObjectivesIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the head API v2 objectives ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *HeadAPIV2ObjectivesIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the head API v2 objectives ID params
func (o *HeadAPIV2ObjectivesIDParams) WithTimeout(timeout time.Duration) *HeadAPIV2ObjectivesIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the head API v2 objectives ID params
func (o *HeadAPIV2ObjectivesIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the head API v2 objectives ID params
func (o *HeadAPIV2ObjectivesIDParams) WithContext(ctx context.Context) *HeadAPIV2ObjectivesIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the head API v2 objectives ID params
func (o *HeadAPIV2ObjectivesIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the head API v2 objectives ID params
func (o *HeadAPIV2ObjectivesIDParams) WithHTTPClient(client *http.Client) *HeadAPIV2ObjectivesIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the head API v2 objectives ID params
func (o *HeadAPIV2ObjectivesIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithExclude adds the exclude to the head API v2 objectives ID params
func (o *HeadAPIV2ObjectivesIDParams) WithExclude(exclude []string) *HeadAPIV2ObjectivesIDParams {
	o.SetExclude(exclude)
	return o
}

// SetExclude adds the exclude to the head API v2 objectives ID params
func (o *HeadAPIV2ObjectivesIDParams) SetExclude(exclude []string) {
	o.Exclude = exclude
}

// WithID adds the id to the head API v2 objectives ID params
func (o *HeadAPIV2ObjectivesIDParams) WithID(id string) *HeadAPIV2ObjectivesIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the head API v2 objectives ID params
func (o *HeadAPIV2ObjectivesIDParams) SetID(id string) {
	o.ID = id
}

// WithInclude adds the include to the head API v2 objectives ID params
func (o *HeadAPIV2ObjectivesIDParams) WithInclude(include []string) *HeadAPIV2ObjectivesIDParams {
	o.SetInclude(include)
	return o
}

// SetInclude adds the include to the head API v2 objectives ID params
func (o *HeadAPIV2ObjectivesIDParams) SetInclude(include []string) {
	o.Include = include
}

// WriteToRequest writes these params to a swagger request
func (o *HeadAPIV2ObjectivesIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Exclude != nil {

		// binding items for exclude
		joinedExclude := o.bindParamExclude(reg)

		// query array param exclude
		if err := r.SetQueryParam("exclude", joinedExclude...); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if o.Include != nil {

		// binding items for include
		joinedInclude := o.bindParamInclude(reg)

		// query array param include
		if err := r.SetQueryParam("include", joinedInclude...); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamHeadAPIV2ObjectivesID binds the parameter exclude
func (o *HeadAPIV2ObjectivesIDParams) bindParamExclude(formats strfmt.Registry) []string {
	excludeIR := o.Exclude

	var excludeIC []string
	for _, excludeIIR := range excludeIR { // explode []string

		excludeIIV := excludeIIR // string as string
		excludeIC = append(excludeIC, excludeIIV)
	}

	// items.CollectionFormat: "multi"
	excludeIS := swag.JoinByFormat(excludeIC, "multi")

	return excludeIS
}

// bindParamHeadAPIV2ObjectivesID binds the parameter include
func (o *HeadAPIV2ObjectivesIDParams) bindParamInclude(formats strfmt.Registry) []string {
	includeIR := o.Include

	var includeIC []string
	for _, includeIIR := range includeIR { // explode []string

		includeIIV := includeIIR // string as string
		includeIC = append(includeIC, includeIIV)
	}

	// items.CollectionFormat: "multi"
	includeIS := swag.JoinByFormat(includeIC, "multi")

	return includeIS
}
