// Code generated by go-swagger; DO NOT EDIT.

package objectives

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"soarca/internal/capability/caldera/api/models"
)

// NewPutAPIV2ObjectivesIDParams creates a new PutAPIV2ObjectivesIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPutAPIV2ObjectivesIDParams() *PutAPIV2ObjectivesIDParams {
	return &PutAPIV2ObjectivesIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPutAPIV2ObjectivesIDParamsWithTimeout creates a new PutAPIV2ObjectivesIDParams object
// with the ability to set a timeout on a request.
func NewPutAPIV2ObjectivesIDParamsWithTimeout(timeout time.Duration) *PutAPIV2ObjectivesIDParams {
	return &PutAPIV2ObjectivesIDParams{
		timeout: timeout,
	}
}

// NewPutAPIV2ObjectivesIDParamsWithContext creates a new PutAPIV2ObjectivesIDParams object
// with the ability to set a context for a request.
func NewPutAPIV2ObjectivesIDParamsWithContext(ctx context.Context) *PutAPIV2ObjectivesIDParams {
	return &PutAPIV2ObjectivesIDParams{
		Context: ctx,
	}
}

// NewPutAPIV2ObjectivesIDParamsWithHTTPClient creates a new PutAPIV2ObjectivesIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPutAPIV2ObjectivesIDParamsWithHTTPClient(client *http.Client) *PutAPIV2ObjectivesIDParams {
	return &PutAPIV2ObjectivesIDParams{
		HTTPClient: client,
	}
}

/*
PutAPIV2ObjectivesIDParams contains all the parameters to send to the API endpoint

	for the put API v2 objectives ID operation.

	Typically these are written to a http.Request.
*/
type PutAPIV2ObjectivesIDParams struct {

	// Body.
	Body *models.PartialObjective

	/* ID.

	   UUID of the Objective to be created or updated
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the put API v2 objectives ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIV2ObjectivesIDParams) WithDefaults() *PutAPIV2ObjectivesIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the put API v2 objectives ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PutAPIV2ObjectivesIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the put API v2 objectives ID params
func (o *PutAPIV2ObjectivesIDParams) WithTimeout(timeout time.Duration) *PutAPIV2ObjectivesIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the put API v2 objectives ID params
func (o *PutAPIV2ObjectivesIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the put API v2 objectives ID params
func (o *PutAPIV2ObjectivesIDParams) WithContext(ctx context.Context) *PutAPIV2ObjectivesIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the put API v2 objectives ID params
func (o *PutAPIV2ObjectivesIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the put API v2 objectives ID params
func (o *PutAPIV2ObjectivesIDParams) WithHTTPClient(client *http.Client) *PutAPIV2ObjectivesIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the put API v2 objectives ID params
func (o *PutAPIV2ObjectivesIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the put API v2 objectives ID params
func (o *PutAPIV2ObjectivesIDParams) WithBody(body *models.PartialObjective) *PutAPIV2ObjectivesIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the put API v2 objectives ID params
func (o *PutAPIV2ObjectivesIDParams) SetBody(body *models.PartialObjective) {
	o.Body = body
}

// WithID adds the id to the put API v2 objectives ID params
func (o *PutAPIV2ObjectivesIDParams) WithID(id string) *PutAPIV2ObjectivesIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the put API v2 objectives ID params
func (o *PutAPIV2ObjectivesIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PutAPIV2ObjectivesIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
