definitions:
  api.PlaybookMeta:
    properties:
      description:
        type: string
      id:
        type: string
      labels:
        items:
          type: string
        type: array
      name:
        type: string
      valid_from:
        type: string
      valid_until:
        type: string
    type: object
  cacao.AgentTarget:
    properties:
      address:
        additionalProperties:
          items:
            type: string
          type: array
        type: object
      agent_target_extensions:
        $ref: '#/definitions/cacao.Extensions'
      authentication_info:
        type: string
      category:
        items:
          type: string
        type: array
      contact:
        $ref: '#/definitions/cacao.Contact'
      description:
        type: string
      http_url:
        type: string
      id:
        type: string
      location:
        $ref: '#/definitions/cacao.CivicLocation'
      logical:
        items:
          type: string
        type: array
      name:
        type: string
      port:
        type: string
      sector:
        type: string
      type:
        type: string
    required:
    - name
    - type
    type: object
  cacao.AuthenticationInformation:
    properties:
      description:
        type: string
      id:
        type: string
      kms:
        type: boolean
      kms_key_identifier:
        type: string
      name:
        type: string
      oauth_header:
        type: string
      password:
        type: string
      private_key:
        type: string
      token:
        type: string
      type:
        type: string
      user_id:
        type: string
      username:
        type: string
    required:
    - type
    type: object
  cacao.CivicLocation:
    properties:
      administrative_area:
        type: string
      building_details:
        type: string
      city:
        type: string
      country:
        type: string
      description:
        type: string
      latitude:
        type: string
      longitude:
        type: string
      name:
        type: string
      network_details:
        type: string
      postal_code:
        type: string
      precision:
        type: string
      region:
        type: string
      street_address:
        type: string
    type: object
  cacao.Command:
    properties:
      command:
        type: string
      command_b64:
        type: string
      content:
        type: string
      content_b64:
        type: string
      description:
        type: string
      headers:
        additionalProperties:
          type: string
        type: object
      playbook_activity:
        type: string
      type:
        type: string
      version:
        type: string
    required:
    - command
    - type
    type: object
  cacao.Contact:
    properties:
      contact_details:
        type: string
      email:
        additionalProperties:
          type: string
        type: object
      phone:
        additionalProperties:
          type: string
        type: object
    type: object
  cacao.DataMarking:
    properties:
      affected_party_notifications:
        type: string
      attribution:
        type: string
      created:
        type: string
      created_by:
        type: string
      description:
        type: string
      encrypt_in_transit:
        type: string
      end_date:
        type: string
      external_references:
        items:
          $ref: '#/definitions/cacao.ExternalReferences'
        type: array
      id:
        type: string
      iep_version:
        type: string
      labels:
        items:
          type: string
        type: array
      marking_extensions:
        $ref: '#/definitions/cacao.Extensions'
      name:
        type: string
      permitted_actions:
        type: string
      revoked:
        type: boolean
      start_date:
        type: string
      statement:
        type: string
      tlp:
        type: string
      tlpv2_level:
        type: string
      type:
        type: string
      unmodified_resale:
        type: string
      valid_from:
        type: string
      valid_until:
        type: string
    required:
    - created
    - created_by
    - id
    - type
    type: object
  cacao.ExtensionDefinition:
    properties:
      created_by:
        type: string
      description:
        type: string
      external_references:
        items:
          $ref: '#/definitions/cacao.ExternalReferences'
        type: array
      name:
        type: string
      schema:
        type: string
      type:
        type: string
      version:
        type: string
    required:
    - created_by
    - schema
    - type
    - version
    type: object
  cacao.Extensions:
    additionalProperties: true
    type: object
  cacao.ExternalReferences:
    properties:
      description:
        type: string
      name:
        type: string
      source:
        type: string
      url:
        type: string
    required:
    - description
    - name
    - source
    - url
    type: object
  cacao.Playbook:
    properties:
      agent_definitions:
        additionalProperties:
          $ref: '#/definitions/cacao.AgentTarget'
        type: object
      authentication_info_definitions:
        additionalProperties:
          $ref: '#/definitions/cacao.AuthenticationInformation'
        type: object
      created:
        type: string
      created_by:
        type: string
      data_marking_definitions:
        additionalProperties:
          $ref: '#/definitions/cacao.DataMarking'
        type: object
      derived_from:
        items:
          type: string
        type: array
      description:
        type: string
      extension_definitions:
        additionalProperties:
          $ref: '#/definitions/cacao.ExtensionDefinition'
        type: object
      external_references:
        items:
          $ref: '#/definitions/cacao.ExternalReferences'
        type: array
      id:
        type: string
      impact:
        type: integer
      labels:
        items:
          type: string
        type: array
      markings:
        items:
          type: string
        type: array
      modified:
        type: string
      name:
        type: string
      playbook_extensions:
        $ref: '#/definitions/cacao.Extensions'
      playbook_types:
        items:
          type: string
        type: array
      playbook_variables:
        additionalProperties:
          $ref: '#/definitions/cacao.Variable'
        type: object
      priority:
        type: integer
      severity:
        type: integer
      spec_version:
        type: string
      target_definitions:
        additionalProperties:
          $ref: '#/definitions/cacao.AgentTarget'
        type: object
      type:
        type: string
      valid_from:
        type: string
      valid_until:
        type: string
      workflow:
        $ref: '#/definitions/cacao.Workflow'
      workflow_exception:
        type: string
      workflow_start:
        type: string
    required:
    - created
    - created_by
    - id
    - modified
    - name
    - spec_version
    - type
    - workflow
    - workflow_start
    type: object
  cacao.Step:
    properties:
      agent:
        type: string
      authentication_info:
        type: string
      cases:
        additionalProperties:
          type: string
        type: object
      commands:
        items:
          $ref: '#/definitions/cacao.Command'
        type: array
      condition:
        type: string
      delay:
        type: integer
      description:
        type: string
      external_references:
        items:
          $ref: '#/definitions/cacao.ExternalReferences'
        type: array
      id:
        type: string
      in_args:
        items:
          type: string
        type: array
      name:
        type: string
      next_steps:
        items:
          type: string
        type: array
      on_completion:
        type: string
      on_failure:
        type: string
      on_false:
        type: string
      on_success:
        type: string
      on_true:
        type: string
      out_args:
        items:
          type: string
        type: array
      owner:
        type: string
      playbook_id:
        type: string
      playbook_version:
        type: string
      step_extensions:
        $ref: '#/definitions/cacao.Extensions'
      step_variables:
        additionalProperties:
          $ref: '#/definitions/cacao.Variable'
        type: object
      switch:
        type: string
      targets:
        items:
          type: string
        type: array
      timeout:
        type: integer
      type:
        type: string
    required:
    - type
    type: object
  cacao.Variable:
    properties:
      constant:
        type: boolean
      description:
        type: string
      external:
        type: boolean
      name:
        type: string
      type:
        type: string
      value:
        type: string
    required:
    - type
    type: object
  cacao.Workflow:
    additionalProperties:
      $ref: '#/definitions/cacao.Step'
    type: object
info:
  contact: {}
paths:
  /playbook/:
    get:
      description: return all stored playbooks default limit:100
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/cacao.Playbook'
            type: array
      summary: gets all the UUIDs for the stored playbooks
      tags:
      - playbook
    post:
      consumes:
      - application/json
      description: submit a new playbook api
      parameters:
      - description: playbook
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/cacao.Playbook'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/cacao.Playbook'
      summary: submit playbook via the api
      tags:
      - playbook
  /playbook/{id}:
    delete:
      consumes:
      - application/json
      description: delete playbook by Id
      parameters:
      - description: playbook ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: delete playbook by Id
      tags:
      - playbook
    get:
      consumes:
      - application/json
      description: get playbook by ID
      parameters:
      - description: playbook ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/cacao.Playbook'
      summary: get CACAO playbook by its ID
      tags:
      - playbook
    put:
      consumes:
      - application/json
      description: update playbook by Id
      parameters:
      - description: playbook Id
        in: path
        name: id
        required: true
        type: string
      - description: playbook
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/cacao.Playbook'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/cacao.Playbook'
      summary: update playbook
      tags:
      - playbook
  /playbook/meta:
    get:
      description: get playbook meta information for playbook
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api.PlaybookMeta'
            type: array
      summary: gets all the meta information for the stored playbooks
      tags:
      - playbook
  /trigger/workflow:
    post:
      consumes:
      - application/json
      description: trigger workflow
      parameters:
      - description: execute playbook by payload
        in: body
        name: playbook
        required: true
        schema:
          $ref: '#/definitions/cacao.Playbook'
      produces:
      - application/json
      responses:
        "200":
          description: '{"execution_id":"uuid","payload":"playbook--uuid"}'
      summary: trigger a workflow with via cacao payload
      tags:
      - trigger
swagger: "2.0"
