name: Compile

on:
  pull_request:
    branches: [ master, development ]

jobs:
  compile:
    name: Cross compile binaries
    runs-on: ubuntu-latest
    container:
      image: golangci/golangci-lint:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Make repo safe
        run: git config --global --add safe.directory /__w/SOARCA/SOARCA

      - name: Install swaggo
        run:  go install github.com/swaggo/swag/cmd/swag@latest 

      - name: Build with make
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          go install github.com/CycloneDX/cyclonedx-gomod/cmd/cyclonedx-gomod@latest
          make compile
          make sbom

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}
          path: bin/*
          retention-days: 1