name: Lint

on:
  pull_request:
    branches: [ master, development ]

jobs:
  build:
    name: Lint go code with golangci
    runs-on: ubuntu-latest
    container:
      image: golangci/golangci-lint:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Make repo safe
        run: git config --global --add safe.directory /__w/SOARCA/SOARCA

      - name: lint
        run: |
          ls -la 
          golangci-lint run --timeout 5m -v
        shell: bash


