name: release

on:
  push:
    tags:
      - [0-9]+.[0-9]+.[0-9]+\-?*

jobs:
  compile:
    name: Cross compile binaries
    runs-on: ubuntu-latest
    container:
      image: golangci/golangci-lint:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Make repo safe
        run: git config --global --add safe.directory /__w/SOARCA/SOARCA

      - name: Install swaggo
        run:  go install github.com/swaggo/swag/cmd/swag@latest 

      - name: Build with make
        run: |
          go install github.com/swaggo/swag/cmd/swag@latest
          go install github.com/CycloneDX/cyclonedx-gomod/cmd/cyclonedx-gomod@latest
          make compile
          make sbom

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.sha }}
          path: bin/*
          retention-days: 1
  
  docker-build:
    needs: compile
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Make repo safe
        run: git config --global --add safe.directory /__w/SOARCA/SOARCA

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download bin
        uses: actions/download-artifact@v4
        with: 
          pattern: ${{ github.sha }}

      - name: Move files to bin folder
        run: |
          mkdir -p bin 
          mv ${{ github.sha }}/* ./bin/

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build image and push to dockerhub
        run: |
          export VERSION=$(git describe --tags --dirty)
          echo $VERSION
          docker build --build-arg VERSION -t $VERSION .
          docker push cossas/soarca:$VERSION