name: Test

on:
  pull_request:
    branches: [ master, development ]

jobs:
  test:
    name: Run ci-tests
    runs-on: ubuntu-latest
    container:
      image: golang:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run tests
        run: |
          apt update
          apt install openssh-server -y
          useradd sshtest
          echo "sshtest:pdKY77qNxpI5MAizirtjCVOcm0KFKIs" | chpasswd
          service ssh start
          make ci-test

