// Code generated by go-swagger; DO NOT EDIT.

package sources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewDeleteAPIV2SourcesIDParams creates a new DeleteAPIV2SourcesIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewDeleteAPIV2SourcesIDParams() *DeleteAPIV2SourcesIDParams {
	return &DeleteAPIV2SourcesIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteAPIV2SourcesIDParamsWithTimeout creates a new DeleteAPIV2SourcesIDParams object
// with the ability to set a timeout on a request.
func NewDeleteAPIV2SourcesIDParamsWithTimeout(timeout time.Duration) *DeleteAPIV2SourcesIDParams {
	return &DeleteAPIV2SourcesIDParams{
		timeout: timeout,
	}
}

// NewDeleteAPIV2SourcesIDParamsWithContext creates a new DeleteAPIV2SourcesIDParams object
// with the ability to set a context for a request.
func NewDeleteAPIV2SourcesIDParamsWithContext(ctx context.Context) *DeleteAPIV2SourcesIDParams {
	return &DeleteAPIV2SourcesIDParams{
		Context: ctx,
	}
}

// NewDeleteAPIV2SourcesIDParamsWithHTTPClient creates a new DeleteAPIV2SourcesIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewDeleteAPIV2SourcesIDParamsWithHTTPClient(client *http.Client) *DeleteAPIV2SourcesIDParams {
	return &DeleteAPIV2SourcesIDParams{
		HTTPClient: client,
	}
}

/*
DeleteAPIV2SourcesIDParams contains all the parameters to send to the API endpoint

	for the delete API v2 sources ID operation.

	Typically these are written to a http.Request.
*/
type DeleteAPIV2SourcesIDParams struct {

	/* ID.

	   The id of the Fact Source to be deleted.
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the delete API v2 sources ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIV2SourcesIDParams) WithDefaults() *DeleteAPIV2SourcesIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the delete API v2 sources ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *DeleteAPIV2SourcesIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the delete API v2 sources ID params
func (o *DeleteAPIV2SourcesIDParams) WithTimeout(timeout time.Duration) *DeleteAPIV2SourcesIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete API v2 sources ID params
func (o *DeleteAPIV2SourcesIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete API v2 sources ID params
func (o *DeleteAPIV2SourcesIDParams) WithContext(ctx context.Context) *DeleteAPIV2SourcesIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete API v2 sources ID params
func (o *DeleteAPIV2SourcesIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete API v2 sources ID params
func (o *DeleteAPIV2SourcesIDParams) WithHTTPClient(client *http.Client) *DeleteAPIV2SourcesIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete API v2 sources ID params
func (o *DeleteAPIV2SourcesIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the delete API v2 sources ID params
func (o *DeleteAPIV2SourcesIDParams) WithID(id string) *DeleteAPIV2SourcesIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the delete API v2 sources ID params
func (o *DeleteAPIV2SourcesIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteAPIV2SourcesIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
