// Code generated by go-swagger; DO NOT EDIT.

package sources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"soarca/pkg/core/capability/caldera/api/models"
)

// GetAPIV2SourcesReader is a Reader for the GetAPIV2Sources structure.
type GetAPIV2SourcesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetAPIV2SourcesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewGetAPIV2SourcesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[GET /api/v2/sources] GetAPIV2Sources", response, response.Code())
	}
}

// NewGetAPIV2SourcesOK creates a GetAPIV2SourcesOK with default headers values
func NewGetAPIV2SourcesOK() *GetAPIV2SourcesOK {
	return &GetAPIV2SourcesOK{}
}

/*
GetAPIV2SourcesOK describes a response with status code 200, with default header values.

Returns a list of all Sources dumped in SourceSchema format.
*/
type GetAPIV2SourcesOK struct {
	Payload []*models.PartialSource
}

// IsSuccess returns true when this get Api v2 sources o k response has a 2xx status code
func (o *GetAPIV2SourcesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this get Api v2 sources o k response has a 3xx status code
func (o *GetAPIV2SourcesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this get Api v2 sources o k response has a 4xx status code
func (o *GetAPIV2SourcesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this get Api v2 sources o k response has a 5xx status code
func (o *GetAPIV2SourcesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this get Api v2 sources o k response a status code equal to that given
func (o *GetAPIV2SourcesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the get Api v2 sources o k response
func (o *GetAPIV2SourcesOK) Code() int {
	return 200
}

func (o *GetAPIV2SourcesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/sources][%d] getApiV2SourcesOK %s", 200, payload)
}

func (o *GetAPIV2SourcesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /api/v2/sources][%d] getApiV2SourcesOK %s", 200, payload)
}

func (o *GetAPIV2SourcesOK) GetPayload() []*models.PartialSource {
	return o.Payload
}

func (o *GetAPIV2SourcesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
