// Code generated by go-swagger; DO NOT EDIT.

package sources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"soarca/pkg/core/capability/caldera/api/models"
)

// NewPatchAPIV2SourcesIDParams creates a new PatchAPIV2SourcesIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewPatchAPIV2SourcesIDParams() *PatchAPIV2SourcesIDParams {
	return &PatchAPIV2SourcesIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewPatchAPIV2SourcesIDParamsWithTimeout creates a new PatchAPIV2SourcesIDParams object
// with the ability to set a timeout on a request.
func NewPatchAPIV2SourcesIDParamsWithTimeout(timeout time.Duration) *PatchAPIV2SourcesIDParams {
	return &PatchAPIV2SourcesIDParams{
		timeout: timeout,
	}
}

// NewPatchAPIV2SourcesIDParamsWithContext creates a new PatchAPIV2SourcesIDParams object
// with the ability to set a context for a request.
func NewPatchAPIV2SourcesIDParamsWithContext(ctx context.Context) *PatchAPIV2SourcesIDParams {
	return &PatchAPIV2SourcesIDParams{
		Context: ctx,
	}
}

// NewPatchAPIV2SourcesIDParamsWithHTTPClient creates a new PatchAPIV2SourcesIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewPatchAPIV2SourcesIDParamsWithHTTPClient(client *http.Client) *PatchAPIV2SourcesIDParams {
	return &PatchAPIV2SourcesIDParams{
		HTTPClient: client,
	}
}

/*
PatchAPIV2SourcesIDParams contains all the parameters to send to the API endpoint

	for the patch API v2 sources ID operation.

	Typically these are written to a http.Request.
*/
type PatchAPIV2SourcesIDParams struct {

	// Body.
	Body *models.PartialSource

	/* ID.

	   The id of the Fact Source.
	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the patch API v2 sources ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchAPIV2SourcesIDParams) WithDefaults() *PatchAPIV2SourcesIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the patch API v2 sources ID params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *PatchAPIV2SourcesIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the patch API v2 sources ID params
func (o *PatchAPIV2SourcesIDParams) WithTimeout(timeout time.Duration) *PatchAPIV2SourcesIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch API v2 sources ID params
func (o *PatchAPIV2SourcesIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch API v2 sources ID params
func (o *PatchAPIV2SourcesIDParams) WithContext(ctx context.Context) *PatchAPIV2SourcesIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch API v2 sources ID params
func (o *PatchAPIV2SourcesIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch API v2 sources ID params
func (o *PatchAPIV2SourcesIDParams) WithHTTPClient(client *http.Client) *PatchAPIV2SourcesIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch API v2 sources ID params
func (o *PatchAPIV2SourcesIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the patch API v2 sources ID params
func (o *PatchAPIV2SourcesIDParams) WithBody(body *models.PartialSource) *PatchAPIV2SourcesIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the patch API v2 sources ID params
func (o *PatchAPIV2SourcesIDParams) SetBody(body *models.PartialSource) {
	o.Body = body
}

// WithID adds the id to the patch API v2 sources ID params
func (o *PatchAPIV2SourcesIDParams) WithID(id string) *PatchAPIV2SourcesIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the patch API v2 sources ID params
func (o *PatchAPIV2SourcesIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PatchAPIV2SourcesIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
