// Code generated by go-swagger; DO NOT EDIT.

package sources

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"soarca/pkg/core/capability/caldera/api/models"
)

// PostAPIV2SourcesReader is a Reader for the PostAPIV2Sources structure.
type PostAPIV2SourcesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostAPIV2SourcesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewPostAPIV2SourcesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		return nil, runtime.NewAPIError("[POST /api/v2/sources] PostAPIV2Sources", response, response.Code())
	}
}

// NewPostAPIV2SourcesOK creates a PostAPIV2SourcesOK with default headers values
func NewPostAPIV2SourcesOK() *PostAPIV2SourcesOK {
	return &PostAPIV2SourcesOK{}
}

/*
PostAPIV2SourcesOK describes a response with status code 200, with default header values.

Returns a single Source dumped in SourceSchema format.
*/
type PostAPIV2SourcesOK struct {
	Payload *models.Source
}

// IsSuccess returns true when this post Api v2 sources o k response has a 2xx status code
func (o *PostAPIV2SourcesOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this post Api v2 sources o k response has a 3xx status code
func (o *PostAPIV2SourcesOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this post Api v2 sources o k response has a 4xx status code
func (o *PostAPIV2SourcesOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this post Api v2 sources o k response has a 5xx status code
func (o *PostAPIV2SourcesOK) IsServerError() bool {
	return false
}

// IsCode returns true when this post Api v2 sources o k response a status code equal to that given
func (o *PostAPIV2SourcesOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the post Api v2 sources o k response
func (o *PostAPIV2SourcesOK) Code() int {
	return 200
}

func (o *PostAPIV2SourcesOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v2/sources][%d] postApiV2SourcesOK %s", 200, payload)
}

func (o *PostAPIV2SourcesOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /api/v2/sources][%d] postApiV2SourcesOK %s", 200, payload)
}

func (o *PostAPIV2SourcesOK) GetPayload() *models.Source {
	return o.Payload
}

func (o *PostAPIV2SourcesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Source)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
